/* CEDEARs negociables en BYMA: ticker, ratio contra el subyacente y nombre del
   instrumento. Sale del listado oficial de BYMA del 3 de septiembre de 2026.

   POR QUE ESTE ARCHIVO EXISTE
   El servicio de precios (data912) publica 983 instrumentos y NO informa el
   ratio de ninguno, ni el nombre. Se verifico sobre la respuesta completa. Asi
   que el precio en dolares de un activo —que se deriva como
   (precio_del_cedear_en_pesos x ratio) / cotizacion_MEP— depende enteramente de
   esta tabla, y la descripcion de un ticker recien cargado tambien.

   COMO SE ACTUALIZA
   BYMA publica el listado en PDF. Cuando salga uno nuevo se reemplaza este
   archivo entero y se actualiza `fecha`. Es el unico lugar que hay que tocar.

   POR QUE IMPORTA MANTENERLO
   Un ratio viejo no produce ningun error visible: devuelve un precio en dolares
   creible y equivocado, en la misma proporcion del cambio. SPY paso de 20:1 a
   60:1 en un split de mayo de 2026 y, con el ratio anterior, una posicion
   comprada a 760 aparecia un 58% abajo cuando en realidad estaba 25% arriba.

   FORMATO
   `r` es el ratio ya resuelto como factor: 20 significa que 20 CEDEARs equivalen
   a una accion. Los inversos —un CEDEAR que equivale a varias acciones— van como
   fraccion (1/3), que es lo que vale cada accion.
   `n` es el nombre del instrumento segun BYMA.

   UNA ADVERTENCIA DEL LISTADO
   XLU figura dos veces en el PDF, con 10:1 y con 15:1. Se toma 15:1, el del
   Utilities Select Sector SPDR Fund, que es el fondo que ese ticker designa. */

window.CEDEARS_BYMA = {
  fuente: 'BYMA — CEDEARs negociables',
  fecha: '2026-09-03',
  instrumentos: {
    AABA: { r: 3, n: 'Altaba Inc.' },
    AAL: { r: 2, n: 'American Airlines Group Inc' },
    AAP: { r: 14, n: 'Advanced Auto Parts Inc' },
    AAPL: { r: 20, n: 'Apple Inc.' },
    ABBV: { r: 10, n: 'AbbVie Inc.' },
    ABEV: { r: 1/3, n: 'Ambev S.A.' },
    ABEV3: { r: 1, n: 'Ambev S.A.' },
    ABNB: { r: 15, n: 'Airbnb Inc' },
    ABT: { r: 4, n: 'Abbott Labs' },
    ACN: { r: 75, n: 'Accenture' },
    ACWI: { r: 26, n: 'iShares MSCI ACWI ETF' },
    ADBE: { r: 44, n: 'Adobe Systems Incorporated' },
    ADGO: { r: 1, n: 'Adecoagro S.A.' },
    ADI: { r: 15, n: 'Analog Devices' },
    ADP: { r: 6, n: 'Automatic Data Processing Inc.' },
    ADS: { r: 22, n: 'Adidas AG' },
    AEG: { r: 1, n: 'Aegon N.V.' },
    AEM: { r: 6, n: 'Agnico Eagle Mines Limited' },
    AI: { r: 5, n: 'C3.AI INC' },
    AIG: { r: 5, n: 'American International Group (AIG)' },
    'AKO.B': { r: 1, n: 'Embotelladora Andina S.A.' },
    ALAB: { r: 44, n: 'Astera Labs Inc' },
    AMAT: { r: 5, n: 'Applied Materials Inc.' },
    AMD: { r: 10, n: 'Advanced Micro Devices, Inc.' },
    AMGN: { r: 30, n: 'Amgen Inc.' },
    AMX: { r: 1, n: 'America Movil' },
    AMZN: { r: 144, n: 'Amazon.Com, Inc.' },
    ANET: { r: 29, n: 'Arista Networks Inc.' },
    ANF: { r: 1, n: 'Abercrombie & Fitch Co' },
    AOCA: { r: 1, n: 'Aluminum Corp Of China' },
    ARCO: { r: 1/2, n: 'Arcos Dorados Holdings Inc.' },
    ARKK: { r: 10, n: 'ARK INNOVATION' },
    ARM: { r: 27, n: 'ARM Holdings Plc' },
    ASML: { r: 146, n: 'ASML HOLDING NV' },
    ASR: { r: 20, n: 'Grupo Aeroportuario Del Sureste , S.A.B. de C.V.' },
    ASTS: { r: 15, n: 'AST SpaceMobile Inc' },
    ATAD: { r: 4, n: 'Pjsc Tatneft' },
    AUY: { r: 1, n: 'Yamana Gold Inc.' },
    AVGO: { r: 39, n: 'Broadcom Inc.' },
    AVY: { r: 18, n: 'Avery Dennison Corp.' },
    AXP: { r: 15, n: 'American Express Co' },
    AZN: { r: 4, n: 'Astrazeneca Plc' },
    B: { r: 2, n: 'Barrick Gold Corp' },
    BA: { r: 24, n: 'The Boeing Company' },
    'BA.C': { r: 4, n: 'Bank Of America Corporation' },
    BABA: { r: 9, n: 'Alibaba Group Holding Limited' },
    BAK: { r: 2, n: 'Braskem SA' },
    BAS: { r: 2, n: 'Basf SE' },
    BAYN: { r: 3, n: 'Bayer AG' },
    BB: { r: 3, n: 'Blackberry Limited' },
    BBAS3: { r: 2, n: 'Banco do Brasil S.A.' },
    BBD: { r: 1, n: 'Banco Bradesco S.A.' },
    BBDC3: { r: 1, n: 'Banco Bradesco S.A.' },
    BBV: { r: 1, n: 'Bilbao Vizcaya Argentaria S.A.' },
    BCS: { r: 1, n: 'Barclays Bank Plc' },
    BHP: { r: 2, n: 'Bhp Group Ltd' },
    BIDU: { r: 11, n: 'Baidu, Inc.' },
    BIIB: { r: 13, n: 'Biogen Inc.' },
    BIOX: { r: 1, n: 'Bioceres Crop Solutions Corp.' },
    BK: { r: 2, n: 'The Bank Of New York Mellon Corp.' },
    BKNG: { r: 700, n: 'Booking' },
    BKR: { r: 7, n: 'Baker Hughes Co' },
    BMNR: { r: 8, n: 'Bitmine Inmersion Technologies, Inc.' },
    BMY: { r: 3, n: 'Bristol-Myers Squibb Company' },
    BNG: { r: 5, n: 'Bunge Limited' },
    BP: { r: 5, n: 'BP PCL' },
    BPA11: { r: 1, n: 'Banco BTG Pactual S.A.' },
    BRFS: { r: 1/3, n: 'BRF S.A.' },
    BRKB: { r: 22, n: 'Berkshire Hathaway Inc.' },
    BSBR: { r: 1, n: 'Banco Santander (Brasil) S.A.' },
    BSN: { r: 20, n: 'Danone' },
    BX: { r: 30, n: 'Blackstone Inc.' },
    C: { r: 3, n: 'Citigroup Inc' },
    CAAP: { r: 1/4, n: 'Corporación America Airports S.A.' },
    CAH: { r: 3, n: 'Cardinal Health Inc' },
    CAJ: { r: 2, n: 'Canon Inc' },
    CAR: { r: 26, n: 'Avis Budget Group Inc.' },
    CAT: { r: 20, n: 'Caterpillar Inc' },
    CBRD: { r: 1, n: 'Companhia Brasileira De Dis NPV ADR' },
    CCJ: { r: 23, n: 'Cameco Corporation' },
    CCL: { r: 3, n: 'Carnival' },
    CDE: { r: 1, n: 'Coeur Mining Inc.' },
    CEG: { r: 45, n: 'CONSTELLATION ENERGY CORPORATION' },
    CIBR: { r: 10, n: 'First Trust NASDAQ Cybersecurity' },
    CL: { r: 3, n: 'Colgate Palmolive Co' },
    CLS: { r: 20, n: 'CELESTICA INC' },
    COIN: { r: 27, n: 'Coinbase Global Inc' },
    COP: { r: 25, n: 'ConocoPhillips' },
    COPX: { r: 14, n: 'Global X Copper Miners ETF' },
    COST: { r: 48, n: 'Costco Wholesale Corp' },
    CRM: { r: 18, n: 'Salesforce Inc.' },
    CRWD: { r: 79, n: 'CrowdStrike Holdings, Inc.' },
    CRWV: { r: 27, n: 'CoreWeave Inc' },
    CS: { r: 1, n: 'Credit Suisse Group' },
    CSCO: { r: 5, n: 'Cisco Systems Inc' },
    CSNA3: { r: 1, n: 'Companhia Siderúrgica Nacional S.A.' },
    CVS: { r: 15, n: 'CVS Health' },
    CVX: { r: 16, n: 'Chevron Corp.' },
    CX: { r: 1, n: 'Cemex S.A.B. de CV' },
    DAL: { r: 8, n: 'Delta Air Lines' },
    DD: { r: 5, n: 'Dupont de Nemours Inc.' },
    DE: { r: 40, n: 'Deere & Co.' },
    DECK: { r: 25, n: 'DECKERS OUTDOOR CORPORATION' },
    DELL: { r: 74, n: 'DELL TECHNOLOGIES INC' },
    DEO: { r: 6, n: 'Diageo PLC' },
    DHR: { r: 54, n: 'Danaher Corp' },
    DIA: { r: 20, n: 'SPDR DOW JONES INDUSTRIAL' },
    DISN: { r: 12, n: 'The Walt Disney Co.' },
    DOCU: { r: 22, n: 'DocuSign Inc.' },
    DOW: { r: 6, n: 'DOW Inc' },
    DTEA: { r: 3, n: 'Deutsche Telekom Ag' },
    E: { r: 4, n: 'Eni Spa' },
    EA: { r: 14, n: 'Electronic Arts Inc' },
    EBAY: { r: 2, n: 'Ebay Inc.' },
    EBR: { r: 1/4, n: 'Centrais Eléctricas Brasileiras S.A. - Eletrobras' },
    ECL: { r: 56, n: 'Ecolab Inc' },
    EEM: { r: 5, n: 'ISHARES MSCI EMERGING MARKET' },
    EFA: { r: 18, n: 'iShares MSCI EAFE ETF' },
    EFX: { r: 16, n: 'Equifax Inc.' },
    ELP: { r: 1/3, n: 'Companhia Paranaense de Energía - COPEL' },
    EOAN: { r: 6, n: 'E.On Se' },
    EQNR: { r: 6, n: 'Equinor Asa' },
    ERIC: { r: 2, n: 'Lm Ericsson Telephone Co.' },
    ERJ: { r: 1, n: 'Embraer-Empresa Brasileira de Aeronáutica S.A.' },
    ESGU: { r: 30, n: 'IShares ESG Aware MSCI USA ETF' },
    ETHA: { r: 5, n: 'ISHARES ETHEREUM TR ETF' },
    ETSY: { r: 16, n: 'Etsy Inc.' },
    EWJ: { r: 14, n: 'iShares MSCI JAPAN ETF' },
    EWY: { r: 50, n: 'iShares MSCI South Korea ETF' },
    EWZ: { r: 2, n: 'ISHARES MSCI BRAZIL CAP' },
    F: { r: 1, n: 'Ford Motor Company' },
    FCX: { r: 3, n: 'Freeport Mcmoran Copper & Gold Inc.' },
    FDX: { r: 10, n: 'Fedex Corp' },
    FISV: { r: 11, n: 'Fiserv, Inc.' },
    FMCC: { r: 1, n: 'Freddie Mac (Federal Home Loan)' },
    FMX: { r: 6, n: 'Fomento Economico Mexicano - Femsa' },
    FNMA: { r: 1, n: 'Fed. Natl, Mortgage - Fannie Mae' },
    FSLR: { r: 18, n: 'First Solar Inc.' },
    FXI: { r: 5, n: 'ISHARES CHINA LARGE-CAP ETF' },
    GDX: { r: 10, n: 'Van Eck Gold Miners ETF/USA' },
    GE: { r: 8, n: 'General Electric Co.' },
    GEV: { r: 180, n: 'GE VERNOVA INC' },
    GFI: { r: 1, n: 'Gold Fields Ltd.' },
    GGB: { r: 1/4, n: 'Gerdau S.A.' },
    GILD: { r: 4, n: 'Gilead Sciences, Inc.' },
    GLD: { r: 50, n: 'ETF SPDR GOLD TRUST' },
    GLNG: { r: 10, n: 'Golar LNG Ltd.' },
    GLOB: { r: 18, n: 'Globant S.A.' },
    GLW: { r: 4, n: 'Corning Inc.' },
    GM: { r: 6, n: 'General Motors Co' },
    GOOGL: { r: 58, n: 'Alphabet Inc.' },
    GPRK: { r: 1, n: 'Geopark Ltd.' },
    GRMN: { r: 3, n: 'Garmin Ltd.' },
    GS: { r: 13, n: 'The Goldman Sachs Group, Inc' },
    GSK: { r: 4, n: 'GSK Plc.' },
    GT: { r: 2, n: 'Goodyear Tire & Rubber co./the' },
    HAL: { r: 2, n: 'Halliburton Co.' },
    HAPV3: { r: 1, n: 'Hapvida Participacoes E Investimentos S.A.' },
    HD: { r: 32, n: 'The Home Depot Inc.' },
    HDB: { r: 2, n: 'Hdfc Bank Limited.' },
    HHPD: { r: 2, n: 'Hon Hai Precision Industry Co. Ltd.' },
    HIMS: { r: 4, n: 'Hims & Hers Health, Inc.' },
    HL: { r: 1, n: 'Hecla Mining Co .' },
    HMC: { r: 1, n: 'Honda Motor Co. Ltd' },
    HMY: { r: 1, n: 'Harmony Gold Mining Company Ltd.' },
    HNPIY: { r: 1, n: 'Huaneng Power Intl' },
    HOG: { r: 3, n: 'Harley-Davidson Inc.' },
    HON: { r: 8, n: 'Honeywell International Inc.' },
    HOOD: { r: 29, n: 'Robinhood Markets Inc' },
    HPQ: { r: 1, n: 'Hp Inc' },
    HSBC: { r: 2, n: 'Hsbc Holdings Plc' },
    HSY: { r: 21, n: 'The Hershey Company' },
    HUT: { r: 5, n: 'Hut 8 Mining Corp.' },
    HWM: { r: 1, n: 'Howmet Aerospace Inc.' },
    IBB: { r: 27, n: 'iShares Nasdaq Biotechnology ETF' },
    IBIT: { r: 10, n: 'ISHARES BITCOIN TRUST' },
    IBKR: { r: 17, n: 'INTERACTIVE BROKERS GROUP INC' },
    IBM: { r: 15, n: 'International Business Machines' },
    IBN: { r: 1, n: 'Icici Bank Ltd.' },
    ICLN: { r: 5, n: 'iShares Global Clean Energy ETF' },
    IEMG: { r: 12, n: 'iShares Core MSCI Emerging Markets ETF' },
    IEUR: { r: 11, n: 'iShares Core MSCI Europe ETF' },
    IFF: { r: 12, n: 'International Flavors & Fragrances Inc.' },
    IJH: { r: 12, n: 'iShares CORE S&P MID-CAP ETF' },
    ILF: { r: 6, n: 'IShares Latin America 40 ETF' },
    INFY: { r: 1, n: 'Infosys Limited' },
    ING: { r: 3, n: 'Ing Groep Nv' },
    INTC: { r: 5, n: 'Intel Corporation' },
    IP: { r: 4, n: 'International Paper Co.' },
    IREN: { r: 12, n: 'Iren Ltd' },
    ISRG: { r: 90, n: 'Intuitive Surgical inc' },
    ITA: { r: 50, n: 'iShares U.S. Aerospace & Defense' },
    ITUB: { r: 1, n: 'Itaú Unibanco Holding S.A.' },
    ITUB3: { r: 1, n: 'Banco Itaú Unibanco S.A' },
    IVE: { r: 40, n: 'iShares S&P 500 Value ETF' },
    IVV: { r: 692, n: 'IShares Core S&P 500 ETF' },
    IVW: { r: 20, n: 'iShares S&P 500 Growth ETF' },
    IWM: { r: 10, n: 'ISHARES TRUST RUSSELL 2000' },
    JCI: { r: 2, n: 'Johnson Controls International' },
    JD: { r: 4, n: 'Jd.Com, Inc.' },
    JMIA: { r: 1, n: 'Adr Jumia Technologies Ag' },
    JNJ: { r: 15, n: 'Johnson & Johnson' },
    JOYY: { r: 5, n: 'JOYY Inc.' },
    JPM: { r: 15, n: 'J.P. Morgan & Chase Co.' },
    KB: { r: 2, n: 'Kb Financial Group Inc.' },
    KEEL: { r: 1/5, n: 'Bitfarms Ltd.' },
    KEP: { r: 1, n: 'Korea Electric Power Corp.' },
    KGC: { r: 1, n: 'Kinross Gold Corp' },
    KLAC: { r: 34, n: 'KLA CORP' },
    KMB: { r: 6, n: 'Kimberly-Clark Corp.' },
    KO: { r: 5, n: 'The Coca Cola Company' },
    KOFM: { r: 2, n: 'Coca-Cola Femsa, S.A.B. De C.V.' },
    LAC: { r: 1, n: 'Lithium Americas Corp' },
    LAR: { r: 1, n: 'Lithium Americas (Argentina) Corp' },
    LFC: { r: 2, n: 'China Life Insurance' },
    LIN: { r: 102, n: 'LINDE PLC' },
    LKOD: { r: 4, n: 'Pjsc Lukoil' },
    LLY: { r: 56, n: 'Eli Lilly and Company' },
    LMT: { r: 20, n: 'Lockheed Martin Corporation' },
    LND: { r: 1, n: 'Brasilagro - Co Brasileira de Propriedades Agrícolas' },
    LRCX: { r: 56, n: 'Lam Research Corp' },
    LREN3: { r: 1, n: 'Lojas Renner S.A.' },
    LVS: { r: 2, n: 'Las Vegas Sands Corp' },
    LYG: { r: 2, n: 'Lloyds Banking Group Plc' },
    MA: { r: 33, n: 'Mastercard Inc.' },
    MBG: { r: 4, n: 'Mercedes-Benz Group AG' },
    MBT: { r: 2, n: 'Mobile Telesystems' },
    MCD: { r: 24, n: 'Mcdonald\'S Corp.' },
    MDLZ: { r: 15, n: 'Mondelez' },
    MDT: { r: 4, n: 'Medtronic Public Limited Company' },
    MELI: { r: 120, n: 'Mercadolibre Inc.' },
    META: { r: 24, n: 'Meta Platforms Inc' },
    MFG: { r: 1, n: 'Mizuho Financial Group' },
    MGLU3: { r: 1, n: 'Magazine Luiza S.A.' },
    MMC: { r: 16, n: 'Marsh & Mclennan Companies Inc.' },
    MMM: { r: 10, n: '3M Company' },
    MO: { r: 4, n: 'Altria Group Inc.' },
    MOS: { r: 5, n: 'The Mosaic Co' },
    MP: { r: 10, n: 'MP Materials Corp.' },
    MRK: { r: 5, n: 'Merck & Co. Inc.' },
    MRNA: { r: 19, n: 'Moderna Inc' },
    MRVL: { r: 14, n: 'Marvell Technology Inc' },
    MS: { r: 41, n: 'MORGAN STANLEY' },
    MSFT: { r: 30, n: 'Microsoft Corp.' },
    MSI: { r: 20, n: 'Motorola Solutions, Inc.' },
    MSTR: { r: 20, n: 'Microstrategy Inc Cl A New' },
    MU: { r: 5, n: 'Micron Technology Inc' },
    MUFG: { r: 1, n: 'Mitsubishi Ufj Financial Group' },
    MUX: { r: 2, n: 'McEwen Mining Inc' },
    NATU3: { r: 1, n: 'NATURA COSMETICOS SA' },
    NBIS: { r: 27, n: 'Nebius Group N.V.' },
    NEC1: { r: 1/3, n: 'Nec Corporation' },
    NEE: { r: 19, n: 'NextEra Energy, Inc.' },
    NEM: { r: 3, n: 'Newmont Corporation' },
    NFLX: { r: 48, n: 'Netflix, Inc.' },
    NG: { r: 1/4, n: 'Novagold Resources INC.' },
    NGG: { r: 2, n: 'National Grid Plc' },
    NIO: { r: 4, n: 'NIO Inc.' },
    NKE: { r: 12, n: 'Nike Inc.' },
    NLM: { r: 2, n: 'Novolipetsk Steel PJSC' },
    NMR: { r: 1, n: 'Nomura Holdings, Inc' },
    NOKA: { r: 1, n: 'Nokia Corporation' },
    NOW: { r: 172, n: 'SERVICENOW INC' },
    NSAN: { r: 1, n: 'Nissan Motor Co., Ltd' },
    NTES: { r: 14, n: 'Netease, Inc' },
    NTRA: { r: 51, n: 'NATERA INC' },
    NU: { r: 2, n: 'NU Holdings Ltd/Cayman Islands' },
    NUE: { r: 16, n: 'Nucor Corp' },
    NVDA: { r: 24, n: 'Nvidia Corporation' },
    NVO: { r: 7, n: 'NOVO NORDISK A/S' },
    NVS: { r: 4, n: 'Novartis Ag' },
    NXE: { r: 1, n: 'Nexgen Energy LTD' },
    O: { r: 13, n: 'Realty Income Corp.' },
    OGZD: { r: 2, n: 'Pjsc Gazprom' },
    OKLO: { r: 28, n: 'Oklo Inc' },
    ONDS: { r: 2, n: 'Ondas Holdings Inc.' },
    ORAN: { r: 1, n: 'Orange S.A.' },
    ORCL: { r: 3, n: 'Oracle Corporation' },
    ORLY: { r: 222, n: 'O\'reilly Automotive Inc' },
    OXY: { r: 5, n: 'Occidental Petroleum Corp.' },
    PAAS: { r: 3, n: 'Pan American Silver Corp.' },
    PAC: { r: 16, n: 'Grupo Aeroportuario del Pacifico, S.A.B. de C.V.' },
    PAGS: { r: 3, n: 'Pagseguro Digital Ltd' },
    PANW: { r: 50, n: 'Palo Alto Networks Inc' },
    PATH: { r: 2, n: 'UIPATH INC' },
    PBI: { r: 1, n: 'Pitney Bowes Inc' },
    PBR: { r: 1, n: 'Petrobras (ADR)' },
    PCAR: { r: 3, n: 'Paccar Inc.' },
    PCRF: { r: 2, n: 'Panasonic Corporation' },
    PDD: { r: 25, n: 'PDD HOLDINGS INC' },
    PEP: { r: 18, n: 'Pepsico Inc' },
    PETR3: { r: 1, n: 'Petrobras - Petróleo Brasileiro S.A.' },
    PFE: { r: 4, n: 'Pfizer Inc.' },
    PG: { r: 15, n: 'Procter & Gamble' },
    PHG: { r: 5, n: 'Koninklijke Philips N.V.' },
    PINS: { r: 7, n: 'Pinterest' },
    PKS: { r: 3, n: 'Posco Holdings Inc.' },
    PLD: { r: 29, n: 'PROLOGIS INC' },
    PLTR: { r: 3, n: 'Palantir Technologies Inc' },
    PM: { r: 18, n: 'Philip Morris International' },
    PRIO3: { r: 2, n: 'Petro Rio S.A.' },
    PSO: { r: 1, n: 'Pearson Plc' },
    PSQ: { r: 8, n: 'PROSHARES SHORT QQQ' },
    PSX: { r: 6, n: 'Phillips 66' },
    PTR: { r: 4, n: 'Petrochina Co Ltd' },
    PYPL: { r: 8, n: 'Paypal Holdings, Inc.' },
    QCOM: { r: 11, n: 'Qualcomm Inc.' },
    QQQ: { r: 20, n: 'INVESCO QQQ TRUST' },
    RACE: { r: 83, n: 'Ferrari' },
    RBLX: { r: 2, n: 'Roblox Corp.' },
    RCTB4: { r: 1/1000, n: 'Telebras PN' },
    RENT3: { r: 2, n: 'Localiza Rent A Car S.A.' },
    RGTI: { r: 2, n: 'RIGETTI COMPUTING INC' },
    RIO: { r: 8, n: 'Rio Tinto Plc' },
    RIOT: { r: 3, n: 'Riot Platforms' },
    RKLB: { r: 12, n: 'Rocket Lab Corp' },
    ROKU: { r: 13, n: 'Roku' },
    ROST: { r: 4, n: 'Ross Stores, Inc.' },
    RSP: { r: 30, n: 'Invesco S&P 500 eql wght ETF' },
    RTX: { r: 5, n: 'Raytheon Technologies Corp' },
    SAN: { r: 1/4, n: 'Banco Santander S.A' },
    SAP: { r: 6, n: 'Sap Se' },
    SATL: { r: 1, n: 'Satellogic Inc.' },
    SBS: { r: 1/2, n: 'Paulo–Sabesp' },
    SBSP3: { r: 1, n: 'Cia Saneamento Básico de SP' },
    SBUX: { r: 12, n: 'Starbucks Corporation' },
    SCCO: { r: 2, n: 'Southern Copper Corp' },
    SCHW: { r: 13, n: 'Charles Schwab' },
    SDA: { r: 2, n: 'SunCar Technology Group Inc' },
    SE: { r: 32, n: 'Sea Ltd.' },
    SH: { r: 8, n: 'PROSHARES SHORT S&P500' },
    SHEL: { r: 2, n: 'Royal Dutch Shell Plc' },
    SHOP: { r: 107, n: 'Shopify Inc.' },
    SHPW: { r: 1/2, n: 'Shapeways Holdings Inc' },
    SHW: { r: 69, n: 'SHERWIN-WILLIAMS CO/THE' },
    SI: { r: 10, n: 'Silvergate Bancorp' },
    SID: { r: 1/8, n: 'Companhia Siderúrgica Nacional' },
    SIEGY: { r: 3, n: 'Siemens Ag Adr' },
    SKHY: { r: 25, n: 'SK HYNIX INC' },
    SLB: { r: 3, n: 'Schlumberger Ltd' },
    SLV: { r: 6, n: 'iShares SILVER TRUST' },
    SMH: { r: 50, n: 'VAN ECK SEMICONDUCTOR ETF' },
    SMSN: { r: 14, n: 'Samsung Electronics Co. Ltd.' },
    SNA: { r: 6, n: 'Snap-On Inc' },
    SNAP: { r: 1, n: 'Snap Inc.' },
    SNDK: { r: 170, n: 'Sandisk Corporation' },
    SNOW: { r: 30, n: 'Snowflake Inc.' },
    SNP: { r: 3, n: 'China Petroleum & Chem' },
    SONY: { r: 8, n: 'Sony Group Corporation' },
    SPCE: { r: 1/2, n: 'Virgin Galactic' },
    SPCX: { r: 50, n: 'SPACE EXPLORATION TECHNOLOGIES CORP.' },
    SPGI: { r: 45, n: 'S&P Global Inc' },
    SPHQ: { r: 14, n: 'Invesco S&P 500 quality ETF' },
    SPOT: { r: 28, n: 'Spotify Technology S.A.' },
    SPXL: { r: 25, n: 'DIREXION DAILY S&P 500 BULL 3X' },
    SPY: { r: 60, n: 'SPDR S&P 500' },
    STLA: { r: 5, n: 'Stellantis' },
    STNE: { r: 3, n: 'StoneCo Ltd' },
    SUZ: { r: 1, n: 'Suzano Papel E Celulose S.A.' },
    SUZB3: { r: 1, n: 'Suzano S.A.' },
    SWKS: { r: 21, n: 'Skyworks Solutions' },
    SYY: { r: 8, n: 'Sysco Corp.' },
    T: { r: 3, n: 'At &T Inc.' },
    TCOM: { r: 2, n: 'TRIP.COM Group Ltd.' },
    TEAM: { r: 47, n: 'ATLASSIAN CORPORATION' },
    TEM: { r: 12, n: 'TEMPUS AI INC' },
    TEN: { r: 1, n: 'Tenaris' },
    TGT: { r: 24, n: 'Target Corporation' },
    TIIAY: { r: 1, n: 'Telecom Italia S.P.A. Ordinary Shares' },
    TIMB: { r: 1, n: 'Tim Participações S.A.' },
    TIMS3: { r: 1, n: 'TIM S.A.' },
    TJX: { r: 22, n: 'TJX Companies Inc/The' },
    TLN: { r: 63, n: 'TALEN ENERGY CORP' },
    TM: { r: 15, n: 'Toyota Motor Corporation' },
    TMO: { r: 22, n: 'Thermo Fisher Scientific Inc.' },
    TMUS: { r: 33, n: 'T-mobile' },
    TQQQ: { r: 25, n: 'ProShares UltraPro QQQ' },
    TRIP: { r: 2, n: 'Tripadvisor, Inc.' },
    TRVV: { r: 6, n: 'The Travelers Cos. Inc.' },
    TSLA: { r: 15, n: 'Tesla, Inc.' },
    TSM: { r: 9, n: 'Taiwan Semiconductor Manufacturing' },
    TTE: { r: 3, n: 'TotalEnergies SE' },
    TTM: { r: 1, n: 'Tata Motors Ltd' },
    TV: { r: 3, n: 'Grupo Televisa S.A.' },
    TWLO: { r: 36, n: 'Twilio Inc' },
    TWTR: { r: 2, n: 'Twitter, Inc.' },
    TXN: { r: 5, n: 'Texas Instruments Inc' },
    TXR: { r: 4, n: 'Ternium S.A.' },
    UAL: { r: 5, n: 'United Airlines Holdings Inc.' },
    UBER: { r: 2, n: 'Uber Technologies Inc.' },
    UGP: { r: 1, n: 'Ultrapar Participações S.A.' },
    UL: { r: 3, n: 'Unilever PLC - Sponsored' },
    UNH: { r: 33, n: 'UnitedHealth Group Inc.' },
    UNP: { r: 20, n: 'Union Pacific Corp.' },
    UPST: { r: 5, n: 'Upstart Hldgs Inc' },
    URA: { r: 5, n: 'Global X Uranium ETF' },
    URBN: { r: 2, n: 'Urban Outfitters INC.' },
    USB: { r: 5, n: 'U.S. Bancorp' },
    USO: { r: 15, n: 'United States Oil Fund' },
    V: { r: 18, n: 'Visa Inc' },
    VALE: { r: 2, n: 'Vale S.A.' },
    VALE3: { r: 1, n: 'Vale S.A.' },
    VEA: { r: 10, n: 'Vanguard FTSE Developed Markets ETF' },
    VIG: { r: 39, n: 'VANGUARD DIVIDEND APPRECIATION' },
    VIST: { r: 3, n: 'Vista Energy S.A.B. de C.V.' },
    VIV: { r: 1, n: 'Telefônica Brasil S.A.' },
    VIVT3: { r: 1, n: 'Telefônica Brasil S.A.' },
    VOD: { r: 1, n: 'Vodafone Group Plc' },
    VRSN: { r: 6, n: 'Verisign, Inc.' },
    VRTX: { r: 101, n: 'VERTEX PHARMACEUTICALS INC' },
    VST: { r: 26, n: 'VISTRA CORPORATION' },
    VXX: { r: 5, n: 'iPath Series B S&P 500 VIX' },
    VZ: { r: 4, n: 'Verizon Communications Inc.' },
    WBA: { r: 3, n: 'Walgreens Boots Alliance Inc.' },
    WBO: { r: 6, n: 'Weibo Corporation' },
    WDC: { r: 92, n: 'WESTERN DIGITAL CORP' },
    WEGE3: { r: 1, n: 'Weg S.A.' },
    WELL: { r: 48, n: 'WELLTOWER INC' },
    WFC: { r: 5, n: 'Wells Fargo & Co.' },
    WMT: { r: 18, n: 'Walmart Inc.' },
    XLB: { r: 18, n: 'The Materials Select Sector SPDR Fund' },
    XLC: { r: 19, n: 'The Communication Services Select Sector SPDR Fund' },
    XLE: { r: 2, n: 'ENERGY SELECT SECTOR SPDR FUND' },
    XLF: { r: 2, n: 'FINANCIAL SELECT SECTOR SPDR FUND' },
    XLI: { r: 28, n: 'The Industrial Select Sector SPDR Fund' },
    XLK: { r: 46, n: 'The Technology Select Sector SPDR Fund' },
    XLP: { r: 16, n: 'The Consumer Staples Select Sector SPDR Fund' },
    XLRE: { r: 9, n: 'The Real Estate Select Sector SPDR Fund' },
    XLU: { r: 15, n: 'Utilities Select Sector SPDR Fund' },
    XLV: { r: 29, n: 'The Health Care Select Sector SPDR Fund' },
    XLY: { r: 43, n: 'The Consumer Discretionary Select Sector SPDR Fund' },
    XME: { r: 30, n: 'State Street SPDR S&P Metals & Mining ETF' },
    XOM: { r: 10, n: 'Exxon Mobil Corporation' },
    XP: { r: 4, n: 'XP Inc' },
    XPEV: { r: 4, n: 'XPENG INC' },
    XROX: { r: 1, n: 'Xerox Holding Corporation' },
    XYZ: { r: 20, n: 'Square Inc.' },
    YELP: { r: 2, n: 'Yelp Inc.' },
    YZCA: { r: 2, n: 'Yanzhou Coal Mining Co. Ltd.' },
    ZM: { r: 47, n: 'Zoom Video Communications Inc.' }
  }
};
