/* CEDEARs negociables en BYMA: ticker, ratio contra el subyacente y nombre del
   instrumento. Sale del listado oficial de BYMA del 3 de septiembre de 2026.

   POR QUE ESTE ARCHIVO EXISTE
   El servicio de precios (data912) publica 983 instrumentos y NO informa el
   ratio de ninguno, ni el nombre. Se verifico sobre la respuesta completa. Asi
   que el precio en dolares de un activo —que se deriva como
   (precio_del_cedear_en_pesos x ratio) / cotizacion_MEP— depende enteramente de
   esta tabla, y la descripcion de un ticker recien cargado tambien.

   COMO SE ACTUALIZA
   BYMA publica el listado en PDF. Cuando salga uno nuevo se reemplaza este
   archivo y se actualiza `fecha`. Es el unico lugar que hay que tocar, pero
   ojo con el sector —ver "EL SECTOR NO VIENE DE BYMA"— y con el filtro de
   "SOLO LO QUE COTIZA", que hay que volver a aplicar.

   SOLO LO QUE COTIZA
   El PDF del 03/09/2026 trae 440 instrumentos. Se sacaron los 44 que no
   aparecian en data912 el 18/09/2026: sin data912 la app no tiene de donde
   traerles precio, asi que tenerlos no servia para nada. Quedan 396. El grupo
   mezcla empresas que dejaron de existir (Twitter, Credit Suisse, Altaba,
   Yamana, Silvergate, Shapeways), las rusas (Gazprom, Lukoil, Tatneft,
   Novolipetsk) y empresas vivas cuyo CEDEAR no opera (BNY Mellon, Electronic
   Arts, Embraer, Mercedes-Benz, Samsung...).
   Sacados: AABA ADS AOCA ATAD AUY BAS BK BRFS BSN CAJ CBRD CS DTEA EA EBR ELP
   EOAN ERJ FMCC HHPD HNPIY LFC LKOD MBG MBT MMC NEC1 NLM NSAN OGZD ORAN PCRF
   PSO PTR RCTB4 SHPW SI SMSN SNP TIIAY TTM TWTR WBA YZCA.
   Al reponer el listado: cruzar contra https://data912.com/live/arg_cedears y
   dejar solo los simbolos que aparecen ahi. Si alguno de estos vuelve a
   operar, vuelve a entrar en esa pasada.

   POR QUE IMPORTA MANTENERLO
   Un ratio viejo no produce ningun error visible: devuelve un precio en dolares
   creible y equivocado, en la misma proporcion del cambio. SPY paso de 20:1 a
   60:1 en un split de mayo de 2026 y, con el ratio anterior, una posicion
   comprada a 760 aparecia un 58% abajo cuando en realidad estaba 25% arriba.

   FORMATO
   `r` es el ratio ya resuelto como factor: 20 significa que 20 CEDEARs equivalen
   a una accion. Los inversos —un CEDEAR que equivale a varias acciones— van como
   fraccion (1/3), que es lo que vale cada accion.
   `n` es el nombre del instrumento segun BYMA.
   `s` es el sector, una de las claves de SECTORES en core.js.

   EL SECTOR NO VIENE DE BYMA
   El PDF no lo informa, ni ninguno de los servicios que usa la app. Se armo una
   vez, el 18/09/2026. De los 396 que quedan: 308 por el mismo simbolo en Yahoo
   Finance, 22 buscando por el nombre de BYMA (revisados uno por uno) y 66 a
   mano —los ETF, nueve acciones brasilenas y mexicanas que Yahoo no encontro
   (PETR3, ITUB3, KOFM...) y tres en las que Yahoo devolvia otra
   empresa: TEN, BAYN y TIMS3—. Los ETF sectoriales (XLE, SMH, IBB...) llevan
   el sector que siguen; los amplios (SPY, QQQ, EWZ...) van a `indices`.
   Al reemplazar el archivo por un listado nuevo hay que conservar `s` de los
   tickers que ya estaban y asignarlo a los nuevos: si falta, el activo aparece
   "sin sector" y el usuario lo tiene que cargar a mano.

   UNA ADVERTENCIA DEL LISTADO
   XLU figura dos veces en el PDF, con 10:1 y con 15:1. Se toma 15:1, el del
   Utilities Select Sector SPDR Fund, que es el fondo que ese ticker designa. */

window.CEDEARS_BYMA = {
  fuente: 'BYMA — CEDEARs negociables',
  fecha: '2026-09-03',
  instrumentos: {
    AAL: { r: 2, n: 'American Airlines Group Inc', s: 'industria' },
    AAP: { r: 14, n: 'Advanced Auto Parts Inc', s: 'consumo_discrecional' },
    AAPL: { r: 20, n: 'Apple Inc.', s: 'tecnologia' },
    ABBV: { r: 10, n: 'AbbVie Inc.', s: 'salud' },
    ABEV: { r: 1/3, n: 'Ambev S.A.', s: 'consumo_basico' },
    ABEV3: { r: 1, n: 'Ambev S.A.', s: 'consumo_basico' },
    ABNB: { r: 15, n: 'Airbnb Inc', s: 'consumo_discrecional' },
    ABT: { r: 4, n: 'Abbott Labs', s: 'salud' },
    ACN: { r: 75, n: 'Accenture', s: 'tecnologia' },
    ACWI: { r: 26, n: 'iShares MSCI ACWI ETF', s: 'indices' },
    ADBE: { r: 44, n: 'Adobe Systems Incorporated', s: 'tecnologia' },
    ADGO: { r: 1, n: 'Adecoagro S.A.', s: 'consumo_basico' },
    ADI: { r: 15, n: 'Analog Devices', s: 'tecnologia' },
    ADP: { r: 6, n: 'Automatic Data Processing Inc.', s: 'tecnologia' },
    AEG: { r: 1, n: 'Aegon N.V.', s: 'financiero' },
    AEM: { r: 6, n: 'Agnico Eagle Mines Limited', s: 'materiales' },
    AI: { r: 5, n: 'C3.AI INC', s: 'tecnologia' },
    AIG: { r: 5, n: 'American International Group (AIG)', s: 'financiero' },
    'AKO.B': { r: 1, n: 'Embotelladora Andina S.A.', s: 'consumo_basico' },
    ALAB: { r: 44, n: 'Astera Labs Inc', s: 'tecnologia' },
    AMAT: { r: 5, n: 'Applied Materials Inc.', s: 'tecnologia' },
    AMD: { r: 10, n: 'Advanced Micro Devices, Inc.', s: 'tecnologia' },
    AMGN: { r: 30, n: 'Amgen Inc.', s: 'salud' },
    AMX: { r: 1, n: 'America Movil', s: 'comunicaciones' },
    AMZN: { r: 144, n: 'Amazon.Com, Inc.', s: 'consumo_discrecional' },
    ANET: { r: 29, n: 'Arista Networks Inc.', s: 'tecnologia' },
    ANF: { r: 1, n: 'Abercrombie & Fitch Co', s: 'consumo_discrecional' },
    ARCO: { r: 1/2, n: 'Arcos Dorados Holdings Inc.', s: 'consumo_discrecional' },
    ARKK: { r: 10, n: 'ARK INNOVATION', s: 'tecnologia' },
    ARM: { r: 27, n: 'ARM Holdings Plc', s: 'tecnologia' },
    ASML: { r: 146, n: 'ASML HOLDING NV', s: 'tecnologia' },
    ASR: { r: 20, n: 'Grupo Aeroportuario Del Sureste , S.A.B. de C.V.', s: 'industria' },
    ASTS: { r: 15, n: 'AST SpaceMobile Inc', s: 'tecnologia' },
    AVGO: { r: 39, n: 'Broadcom Inc.', s: 'tecnologia' },
    AVY: { r: 18, n: 'Avery Dennison Corp.', s: 'consumo_discrecional' },
    AXP: { r: 15, n: 'American Express Co', s: 'financiero' },
    AZN: { r: 4, n: 'Astrazeneca Plc', s: 'salud' },
    B: { r: 2, n: 'Barrick Gold Corp', s: 'materiales' },
    BA: { r: 24, n: 'The Boeing Company', s: 'industria' },
    'BA.C': { r: 4, n: 'Bank Of America Corporation', s: 'financiero' },
    BABA: { r: 9, n: 'Alibaba Group Holding Limited', s: 'consumo_discrecional' },
    BAK: { r: 2, n: 'Braskem SA', s: 'materiales' },
    BAYN: { r: 3, n: 'Bayer AG', s: 'salud' },
    BB: { r: 3, n: 'Blackberry Limited', s: 'tecnologia' },
    BBAS3: { r: 2, n: 'Banco do Brasil S.A.', s: 'financiero' },
    BBD: { r: 1, n: 'Banco Bradesco S.A.', s: 'financiero' },
    BBDC3: { r: 1, n: 'Banco Bradesco S.A.', s: 'financiero' },
    BBV: { r: 1, n: 'Bilbao Vizcaya Argentaria S.A.', s: 'financiero' },
    BCS: { r: 1, n: 'Barclays Bank Plc', s: 'financiero' },
    BHP: { r: 2, n: 'Bhp Group Ltd', s: 'materiales' },
    BIDU: { r: 11, n: 'Baidu, Inc.', s: 'comunicaciones' },
    BIIB: { r: 13, n: 'Biogen Inc.', s: 'salud' },
    BIOX: { r: 1, n: 'Bioceres Crop Solutions Corp.', s: 'materiales' },
    BKNG: { r: 700, n: 'Booking', s: 'consumo_discrecional' },
    BKR: { r: 7, n: 'Baker Hughes Co', s: 'energia' },
    BMNR: { r: 8, n: 'Bitmine Inmersion Technologies, Inc.', s: 'financiero' },
    BMY: { r: 3, n: 'Bristol-Myers Squibb Company', s: 'salud' },
    BNG: { r: 5, n: 'Bunge Limited', s: 'consumo_basico' },
    BP: { r: 5, n: 'BP PCL', s: 'energia' },
    BPA11: { r: 1, n: 'Banco BTG Pactual S.A.', s: 'financiero' },
    BRKB: { r: 22, n: 'Berkshire Hathaway Inc.', s: 'financiero' },
    BSBR: { r: 1, n: 'Banco Santander (Brasil) S.A.', s: 'financiero' },
    BX: { r: 30, n: 'Blackstone Inc.', s: 'financiero' },
    C: { r: 3, n: 'Citigroup Inc', s: 'financiero' },
    CAAP: { r: 1/4, n: 'Corporación America Airports S.A.', s: 'industria' },
    CAH: { r: 3, n: 'Cardinal Health Inc', s: 'salud' },
    CAR: { r: 26, n: 'Avis Budget Group Inc.', s: 'industria' },
    CAT: { r: 20, n: 'Caterpillar Inc', s: 'industria' },
    CCJ: { r: 23, n: 'Cameco Corporation', s: 'energia' },
    CCL: { r: 3, n: 'Carnival', s: 'consumo_discrecional' },
    CDE: { r: 1, n: 'Coeur Mining Inc.', s: 'materiales' },
    CEG: { r: 45, n: 'CONSTELLATION ENERGY CORPORATION', s: 'servicios_publicos' },
    CIBR: { r: 10, n: 'First Trust NASDAQ Cybersecurity', s: 'tecnologia' },
    CL: { r: 3, n: 'Colgate Palmolive Co', s: 'consumo_basico' },
    CLS: { r: 20, n: 'CELESTICA INC', s: 'tecnologia' },
    COIN: { r: 27, n: 'Coinbase Global Inc', s: 'financiero' },
    COP: { r: 25, n: 'ConocoPhillips', s: 'energia' },
    COPX: { r: 14, n: 'Global X Copper Miners ETF', s: 'materiales' },
    COST: { r: 48, n: 'Costco Wholesale Corp', s: 'consumo_basico' },
    CRM: { r: 18, n: 'Salesforce Inc.', s: 'tecnologia' },
    CRWD: { r: 79, n: 'CrowdStrike Holdings, Inc.', s: 'tecnologia' },
    CRWV: { r: 27, n: 'CoreWeave Inc', s: 'tecnologia' },
    CSCO: { r: 5, n: 'Cisco Systems Inc', s: 'tecnologia' },
    CSNA3: { r: 1, n: 'Companhia Siderúrgica Nacional S.A.', s: 'materiales' },
    CVS: { r: 15, n: 'CVS Health', s: 'salud' },
    CVX: { r: 16, n: 'Chevron Corp.', s: 'energia' },
    CX: { r: 1, n: 'Cemex S.A.B. de CV', s: 'materiales' },
    DAL: { r: 8, n: 'Delta Air Lines', s: 'industria' },
    DD: { r: 5, n: 'Dupont de Nemours Inc.', s: 'materiales' },
    DE: { r: 40, n: 'Deere & Co.', s: 'industria' },
    DECK: { r: 25, n: 'DECKERS OUTDOOR CORPORATION', s: 'consumo_discrecional' },
    DELL: { r: 74, n: 'DELL TECHNOLOGIES INC', s: 'tecnologia' },
    DEO: { r: 6, n: 'Diageo PLC', s: 'consumo_basico' },
    DHR: { r: 54, n: 'Danaher Corp', s: 'salud' },
    DIA: { r: 20, n: 'SPDR DOW JONES INDUSTRIAL', s: 'indices' },
    DISN: { r: 12, n: 'The Walt Disney Co.', s: 'comunicaciones' },
    DOCU: { r: 22, n: 'DocuSign Inc.', s: 'tecnologia' },
    DOW: { r: 6, n: 'DOW Inc', s: 'materiales' },
    E: { r: 4, n: 'Eni Spa', s: 'energia' },
    EBAY: { r: 2, n: 'Ebay Inc.', s: 'consumo_discrecional' },
    ECL: { r: 56, n: 'Ecolab Inc', s: 'materiales' },
    EEM: { r: 5, n: 'ISHARES MSCI EMERGING MARKET', s: 'indices' },
    EFA: { r: 18, n: 'iShares MSCI EAFE ETF', s: 'indices' },
    EFX: { r: 16, n: 'Equifax Inc.', s: 'industria' },
    EQNR: { r: 6, n: 'Equinor Asa', s: 'energia' },
    ERIC: { r: 2, n: 'Lm Ericsson Telephone Co.', s: 'tecnologia' },
    ESGU: { r: 30, n: 'IShares ESG Aware MSCI USA ETF', s: 'indices' },
    ETHA: { r: 5, n: 'ISHARES ETHEREUM TR ETF', s: 'cripto' },
    ETSY: { r: 16, n: 'Etsy Inc.', s: 'consumo_discrecional' },
    EWJ: { r: 14, n: 'iShares MSCI JAPAN ETF', s: 'indices' },
    EWY: { r: 50, n: 'iShares MSCI South Korea ETF', s: 'indices' },
    EWZ: { r: 2, n: 'ISHARES MSCI BRAZIL CAP', s: 'indices' },
    F: { r: 1, n: 'Ford Motor Company', s: 'consumo_discrecional' },
    FCX: { r: 3, n: 'Freeport Mcmoran Copper & Gold Inc.', s: 'materiales' },
    FDX: { r: 10, n: 'Fedex Corp', s: 'industria' },
    FISV: { r: 11, n: 'Fiserv, Inc.', s: 'tecnologia' },
    FMX: { r: 6, n: 'Fomento Economico Mexicano - Femsa', s: 'consumo_basico' },
    FNMA: { r: 1, n: 'Fed. Natl, Mortgage - Fannie Mae', s: 'financiero' },
    FSLR: { r: 18, n: 'First Solar Inc.', s: 'tecnologia' },
    FXI: { r: 5, n: 'ISHARES CHINA LARGE-CAP ETF', s: 'indices' },
    GDX: { r: 10, n: 'Van Eck Gold Miners ETF/USA', s: 'materiales' },
    GE: { r: 8, n: 'General Electric Co.', s: 'industria' },
    GEV: { r: 180, n: 'GE VERNOVA INC', s: 'industria' },
    GFI: { r: 1, n: 'Gold Fields Ltd.', s: 'materiales' },
    GGB: { r: 1/4, n: 'Gerdau S.A.', s: 'materiales' },
    GILD: { r: 4, n: 'Gilead Sciences, Inc.', s: 'salud' },
    GLD: { r: 50, n: 'ETF SPDR GOLD TRUST', s: 'commodities' },
    GLNG: { r: 10, n: 'Golar LNG Ltd.', s: 'energia' },
    GLOB: { r: 18, n: 'Globant S.A.', s: 'tecnologia' },
    GLW: { r: 4, n: 'Corning Inc.', s: 'tecnologia' },
    GM: { r: 6, n: 'General Motors Co', s: 'consumo_discrecional' },
    GOOGL: { r: 58, n: 'Alphabet Inc.', s: 'comunicaciones' },
    GPRK: { r: 1, n: 'Geopark Ltd.', s: 'energia' },
    GRMN: { r: 3, n: 'Garmin Ltd.', s: 'tecnologia' },
    GS: { r: 13, n: 'The Goldman Sachs Group, Inc', s: 'financiero' },
    GSK: { r: 4, n: 'GSK Plc.', s: 'salud' },
    GT: { r: 2, n: 'Goodyear Tire & Rubber co./the', s: 'consumo_discrecional' },
    HAL: { r: 2, n: 'Halliburton Co.', s: 'energia' },
    HAPV3: { r: 1, n: 'Hapvida Participacoes E Investimentos S.A.', s: 'salud' },
    HD: { r: 32, n: 'The Home Depot Inc.', s: 'consumo_discrecional' },
    HDB: { r: 2, n: 'Hdfc Bank Limited.', s: 'financiero' },
    HIMS: { r: 4, n: 'Hims & Hers Health, Inc.', s: 'salud' },
    HL: { r: 1, n: 'Hecla Mining Co .', s: 'materiales' },
    HMC: { r: 1, n: 'Honda Motor Co. Ltd', s: 'consumo_discrecional' },
    HMY: { r: 1, n: 'Harmony Gold Mining Company Ltd.', s: 'materiales' },
    HOG: { r: 3, n: 'Harley-Davidson Inc.', s: 'consumo_discrecional' },
    HON: { r: 8, n: 'Honeywell International Inc.', s: 'industria' },
    HOOD: { r: 29, n: 'Robinhood Markets Inc', s: 'financiero' },
    HPQ: { r: 1, n: 'Hp Inc', s: 'tecnologia' },
    HSBC: { r: 2, n: 'Hsbc Holdings Plc', s: 'financiero' },
    HSY: { r: 21, n: 'The Hershey Company', s: 'consumo_basico' },
    HUT: { r: 5, n: 'Hut 8 Mining Corp.', s: 'financiero' },
    HWM: { r: 1, n: 'Howmet Aerospace Inc.', s: 'industria' },
    IBB: { r: 27, n: 'iShares Nasdaq Biotechnology ETF', s: 'salud' },
    IBIT: { r: 10, n: 'ISHARES BITCOIN TRUST', s: 'cripto' },
    IBKR: { r: 17, n: 'INTERACTIVE BROKERS GROUP INC', s: 'financiero' },
    IBM: { r: 15, n: 'International Business Machines', s: 'tecnologia' },
    IBN: { r: 1, n: 'Icici Bank Ltd.', s: 'financiero' },
    ICLN: { r: 5, n: 'iShares Global Clean Energy ETF', s: 'energia' },
    IEMG: { r: 12, n: 'iShares Core MSCI Emerging Markets ETF', s: 'indices' },
    IEUR: { r: 11, n: 'iShares Core MSCI Europe ETF', s: 'indices' },
    IFF: { r: 12, n: 'International Flavors & Fragrances Inc.', s: 'materiales' },
    IJH: { r: 12, n: 'iShares CORE S&P MID-CAP ETF', s: 'indices' },
    ILF: { r: 6, n: 'IShares Latin America 40 ETF', s: 'indices' },
    INFY: { r: 1, n: 'Infosys Limited', s: 'tecnologia' },
    ING: { r: 3, n: 'Ing Groep Nv', s: 'financiero' },
    INTC: { r: 5, n: 'Intel Corporation', s: 'tecnologia' },
    IP: { r: 4, n: 'International Paper Co.', s: 'consumo_discrecional' },
    IREN: { r: 12, n: 'Iren Ltd', s: 'financiero' },
    ISRG: { r: 90, n: 'Intuitive Surgical inc', s: 'salud' },
    ITA: { r: 50, n: 'iShares U.S. Aerospace & Defense', s: 'industria' },
    ITUB: { r: 1, n: 'Itaú Unibanco Holding S.A.', s: 'financiero' },
    ITUB3: { r: 1, n: 'Banco Itaú Unibanco S.A', s: 'financiero' },
    IVE: { r: 40, n: 'iShares S&P 500 Value ETF', s: 'indices' },
    IVV: { r: 692, n: 'IShares Core S&P 500 ETF', s: 'indices' },
    IVW: { r: 20, n: 'iShares S&P 500 Growth ETF', s: 'indices' },
    IWM: { r: 10, n: 'ISHARES TRUST RUSSELL 2000', s: 'indices' },
    JCI: { r: 2, n: 'Johnson Controls International', s: 'industria' },
    JD: { r: 4, n: 'Jd.Com, Inc.', s: 'consumo_discrecional' },
    JMIA: { r: 1, n: 'Adr Jumia Technologies Ag', s: 'consumo_discrecional' },
    JNJ: { r: 15, n: 'Johnson & Johnson', s: 'salud' },
    JOYY: { r: 5, n: 'JOYY Inc.', s: 'comunicaciones' },
    JPM: { r: 15, n: 'J.P. Morgan & Chase Co.', s: 'financiero' },
    KB: { r: 2, n: 'Kb Financial Group Inc.', s: 'financiero' },
    KEEL: { r: 1/5, n: 'Bitfarms Ltd.', s: 'tecnologia' },
    KEP: { r: 1, n: 'Korea Electric Power Corp.', s: 'servicios_publicos' },
    KGC: { r: 1, n: 'Kinross Gold Corp', s: 'materiales' },
    KLAC: { r: 34, n: 'KLA CORP', s: 'tecnologia' },
    KMB: { r: 6, n: 'Kimberly-Clark Corp.', s: 'consumo_basico' },
    KO: { r: 5, n: 'The Coca Cola Company', s: 'consumo_basico' },
    KOFM: { r: 2, n: 'Coca-Cola Femsa, S.A.B. De C.V.', s: 'consumo_basico' },
    LAC: { r: 1, n: 'Lithium Americas Corp', s: 'materiales' },
    LAR: { r: 1, n: 'Lithium Americas (Argentina) Corp', s: 'materiales' },
    LIN: { r: 102, n: 'LINDE PLC', s: 'materiales' },
    LLY: { r: 56, n: 'Eli Lilly and Company', s: 'salud' },
    LMT: { r: 20, n: 'Lockheed Martin Corporation', s: 'industria' },
    LND: { r: 1, n: 'Brasilagro - Co Brasileira de Propriedades Agrícolas', s: 'consumo_basico' },
    LRCX: { r: 56, n: 'Lam Research Corp', s: 'tecnologia' },
    LREN3: { r: 1, n: 'Lojas Renner S.A.', s: 'consumo_discrecional' },
    LVS: { r: 2, n: 'Las Vegas Sands Corp', s: 'consumo_discrecional' },
    LYG: { r: 2, n: 'Lloyds Banking Group Plc', s: 'financiero' },
    MA: { r: 33, n: 'Mastercard Inc.', s: 'financiero' },
    MCD: { r: 24, n: 'Mcdonald\'S Corp.', s: 'consumo_discrecional' },
    MDLZ: { r: 15, n: 'Mondelez', s: 'consumo_basico' },
    MDT: { r: 4, n: 'Medtronic Public Limited Company', s: 'salud' },
    MELI: { r: 120, n: 'Mercadolibre Inc.', s: 'consumo_discrecional' },
    META: { r: 24, n: 'Meta Platforms Inc', s: 'comunicaciones' },
    MFG: { r: 1, n: 'Mizuho Financial Group', s: 'financiero' },
    MGLU3: { r: 1, n: 'Magazine Luiza S.A.', s: 'consumo_discrecional' },
    MMM: { r: 10, n: '3M Company', s: 'industria' },
    MO: { r: 4, n: 'Altria Group Inc.', s: 'consumo_basico' },
    MOS: { r: 5, n: 'The Mosaic Co', s: 'materiales' },
    MP: { r: 10, n: 'MP Materials Corp.', s: 'materiales' },
    MRK: { r: 5, n: 'Merck & Co. Inc.', s: 'salud' },
    MRNA: { r: 19, n: 'Moderna Inc', s: 'salud' },
    MRVL: { r: 14, n: 'Marvell Technology Inc', s: 'tecnologia' },
    MS: { r: 41, n: 'MORGAN STANLEY', s: 'financiero' },
    MSFT: { r: 30, n: 'Microsoft Corp.', s: 'tecnologia' },
    MSI: { r: 20, n: 'Motorola Solutions, Inc.', s: 'tecnologia' },
    MSTR: { r: 20, n: 'Microstrategy Inc Cl A New', s: 'tecnologia' },
    MU: { r: 5, n: 'Micron Technology Inc', s: 'tecnologia' },
    MUFG: { r: 1, n: 'Mitsubishi Ufj Financial Group', s: 'financiero' },
    MUX: { r: 2, n: 'McEwen Mining Inc', s: 'materiales' },
    NATU3: { r: 1, n: 'NATURA COSMETICOS SA', s: 'consumo_basico' },
    NBIS: { r: 27, n: 'Nebius Group N.V.', s: 'comunicaciones' },
    NEE: { r: 19, n: 'NextEra Energy, Inc.', s: 'servicios_publicos' },
    NEM: { r: 3, n: 'Newmont Corporation', s: 'materiales' },
    NFLX: { r: 48, n: 'Netflix, Inc.', s: 'comunicaciones' },
    NG: { r: 1/4, n: 'Novagold Resources INC.', s: 'materiales' },
    NGG: { r: 2, n: 'National Grid Plc', s: 'servicios_publicos' },
    NIO: { r: 4, n: 'NIO Inc.', s: 'consumo_discrecional' },
    NKE: { r: 12, n: 'Nike Inc.', s: 'consumo_discrecional' },
    NMR: { r: 1, n: 'Nomura Holdings, Inc', s: 'financiero' },
    NOKA: { r: 1, n: 'Nokia Corporation', s: 'tecnologia' },
    NOW: { r: 172, n: 'SERVICENOW INC', s: 'tecnologia' },
    NTES: { r: 14, n: 'Netease, Inc', s: 'comunicaciones' },
    NTRA: { r: 51, n: 'NATERA INC', s: 'salud' },
    NU: { r: 2, n: 'NU Holdings Ltd/Cayman Islands', s: 'financiero' },
    NUE: { r: 16, n: 'Nucor Corp', s: 'materiales' },
    NVDA: { r: 24, n: 'Nvidia Corporation', s: 'tecnologia' },
    NVO: { r: 7, n: 'NOVO NORDISK A/S', s: 'salud' },
    NVS: { r: 4, n: 'Novartis Ag', s: 'salud' },
    NXE: { r: 1, n: 'Nexgen Energy LTD', s: 'energia' },
    O: { r: 13, n: 'Realty Income Corp.', s: 'inmobiliario' },
    OKLO: { r: 28, n: 'Oklo Inc', s: 'servicios_publicos' },
    ONDS: { r: 2, n: 'Ondas Holdings Inc.', s: 'tecnologia' },
    ORCL: { r: 3, n: 'Oracle Corporation', s: 'tecnologia' },
    ORLY: { r: 222, n: 'O\'reilly Automotive Inc', s: 'consumo_discrecional' },
    OXY: { r: 5, n: 'Occidental Petroleum Corp.', s: 'energia' },
    PAAS: { r: 3, n: 'Pan American Silver Corp.', s: 'materiales' },
    PAC: { r: 16, n: 'Grupo Aeroportuario del Pacifico, S.A.B. de C.V.', s: 'industria' },
    PAGS: { r: 3, n: 'Pagseguro Digital Ltd', s: 'tecnologia' },
    PANW: { r: 50, n: 'Palo Alto Networks Inc', s: 'tecnologia' },
    PATH: { r: 2, n: 'UIPATH INC', s: 'tecnologia' },
    PBI: { r: 1, n: 'Pitney Bowes Inc', s: 'industria' },
    PBR: { r: 1, n: 'Petrobras (ADR)', s: 'energia' },
    PCAR: { r: 3, n: 'Paccar Inc.', s: 'industria' },
    PDD: { r: 25, n: 'PDD HOLDINGS INC', s: 'consumo_discrecional' },
    PEP: { r: 18, n: 'Pepsico Inc', s: 'consumo_basico' },
    PETR3: { r: 1, n: 'Petrobras - Petróleo Brasileiro S.A.', s: 'energia' },
    PFE: { r: 4, n: 'Pfizer Inc.', s: 'salud' },
    PG: { r: 15, n: 'Procter & Gamble', s: 'consumo_basico' },
    PHG: { r: 5, n: 'Koninklijke Philips N.V.', s: 'salud' },
    PINS: { r: 7, n: 'Pinterest', s: 'comunicaciones' },
    PKS: { r: 3, n: 'Posco Holdings Inc.', s: 'materiales' },
    PLD: { r: 29, n: 'PROLOGIS INC', s: 'inmobiliario' },
    PLTR: { r: 3, n: 'Palantir Technologies Inc', s: 'tecnologia' },
    PM: { r: 18, n: 'Philip Morris International', s: 'consumo_basico' },
    PRIO3: { r: 2, n: 'Petro Rio S.A.', s: 'energia' },
    PSQ: { r: 8, n: 'PROSHARES SHORT QQQ', s: 'indices' },
    PSX: { r: 6, n: 'Phillips 66', s: 'energia' },
    PYPL: { r: 8, n: 'Paypal Holdings, Inc.', s: 'financiero' },
    QCOM: { r: 11, n: 'Qualcomm Inc.', s: 'tecnologia' },
    QQQ: { r: 20, n: 'INVESCO QQQ TRUST', s: 'indices' },
    RACE: { r: 83, n: 'Ferrari', s: 'consumo_discrecional' },
    RBLX: { r: 2, n: 'Roblox Corp.', s: 'comunicaciones' },
    RENT3: { r: 2, n: 'Localiza Rent A Car S.A.', s: 'industria' },
    RGTI: { r: 2, n: 'RIGETTI COMPUTING INC', s: 'tecnologia' },
    RIO: { r: 8, n: 'Rio Tinto Plc', s: 'materiales' },
    RIOT: { r: 3, n: 'Riot Platforms', s: 'financiero' },
    RKLB: { r: 12, n: 'Rocket Lab Corp', s: 'industria' },
    ROKU: { r: 13, n: 'Roku', s: 'comunicaciones' },
    ROST: { r: 4, n: 'Ross Stores, Inc.', s: 'consumo_discrecional' },
    RSP: { r: 30, n: 'Invesco S&P 500 eql wght ETF', s: 'indices' },
    RTX: { r: 5, n: 'Raytheon Technologies Corp', s: 'industria' },
    SAN: { r: 1/4, n: 'Banco Santander S.A', s: 'financiero' },
    SAP: { r: 6, n: 'Sap Se', s: 'tecnologia' },
    SATL: { r: 1, n: 'Satellogic Inc.', s: 'industria' },
    SBS: { r: 1/2, n: 'Paulo–Sabesp', s: 'servicios_publicos' },
    SBSP3: { r: 1, n: 'Cia Saneamento Básico de SP', s: 'servicios_publicos' },
    SBUX: { r: 12, n: 'Starbucks Corporation', s: 'consumo_discrecional' },
    SCCO: { r: 2, n: 'Southern Copper Corp', s: 'materiales' },
    SCHW: { r: 13, n: 'Charles Schwab', s: 'financiero' },
    SDA: { r: 2, n: 'SunCar Technology Group Inc', s: 'consumo_discrecional' },
    SE: { r: 32, n: 'Sea Ltd.', s: 'consumo_discrecional' },
    SH: { r: 8, n: 'PROSHARES SHORT S&P500', s: 'indices' },
    SHEL: { r: 2, n: 'Royal Dutch Shell Plc', s: 'energia' },
    SHOP: { r: 107, n: 'Shopify Inc.', s: 'tecnologia' },
    SHW: { r: 69, n: 'SHERWIN-WILLIAMS CO/THE', s: 'materiales' },
    SID: { r: 1/8, n: 'Companhia Siderúrgica Nacional', s: 'materiales' },
    SIEGY: { r: 3, n: 'Siemens Ag Adr', s: 'industria' },
    SKHY: { r: 25, n: 'SK HYNIX INC', s: 'tecnologia' },
    SLB: { r: 3, n: 'Schlumberger Ltd', s: 'energia' },
    SLV: { r: 6, n: 'iShares SILVER TRUST', s: 'commodities' },
    SMH: { r: 50, n: 'VAN ECK SEMICONDUCTOR ETF', s: 'tecnologia' },
    SNA: { r: 6, n: 'Snap-On Inc', s: 'industria' },
    SNAP: { r: 1, n: 'Snap Inc.', s: 'comunicaciones' },
    SNDK: { r: 170, n: 'Sandisk Corporation', s: 'tecnologia' },
    SNOW: { r: 30, n: 'Snowflake Inc.', s: 'tecnologia' },
    SONY: { r: 8, n: 'Sony Group Corporation', s: 'tecnologia' },
    SPCE: { r: 1/2, n: 'Virgin Galactic', s: 'industria' },
    SPCX: { r: 50, n: 'SPACE EXPLORATION TECHNOLOGIES CORP.', s: 'industria' },
    SPGI: { r: 45, n: 'S&P Global Inc', s: 'financiero' },
    SPHQ: { r: 14, n: 'Invesco S&P 500 quality ETF', s: 'indices' },
    SPOT: { r: 28, n: 'Spotify Technology S.A.', s: 'comunicaciones' },
    SPXL: { r: 25, n: 'DIREXION DAILY S&P 500 BULL 3X', s: 'indices' },
    SPY: { r: 60, n: 'SPDR S&P 500', s: 'indices' },
    STLA: { r: 5, n: 'Stellantis', s: 'consumo_discrecional' },
    STNE: { r: 3, n: 'StoneCo Ltd', s: 'tecnologia' },
    SUZ: { r: 1, n: 'Suzano Papel E Celulose S.A.', s: 'materiales' },
    SUZB3: { r: 1, n: 'Suzano S.A.', s: 'materiales' },
    SWKS: { r: 21, n: 'Skyworks Solutions', s: 'tecnologia' },
    SYY: { r: 8, n: 'Sysco Corp.', s: 'consumo_basico' },
    T: { r: 3, n: 'At &T Inc.', s: 'comunicaciones' },
    TCOM: { r: 2, n: 'TRIP.COM Group Ltd.', s: 'consumo_discrecional' },
    TEAM: { r: 47, n: 'ATLASSIAN CORPORATION', s: 'tecnologia' },
    TEM: { r: 12, n: 'TEMPUS AI INC', s: 'salud' },
    TEN: { r: 1, n: 'Tenaris', s: 'energia' },
    TGT: { r: 24, n: 'Target Corporation', s: 'consumo_basico' },
    TIMB: { r: 1, n: 'Tim Participações S.A.', s: 'comunicaciones' },
    TIMS3: { r: 1, n: 'TIM S.A.', s: 'comunicaciones' },
    TJX: { r: 22, n: 'TJX Companies Inc/The', s: 'consumo_discrecional' },
    TLN: { r: 63, n: 'TALEN ENERGY CORP', s: 'servicios_publicos' },
    TM: { r: 15, n: 'Toyota Motor Corporation', s: 'consumo_discrecional' },
    TMO: { r: 22, n: 'Thermo Fisher Scientific Inc.', s: 'salud' },
    TMUS: { r: 33, n: 'T-mobile', s: 'comunicaciones' },
    TQQQ: { r: 25, n: 'ProShares UltraPro QQQ', s: 'indices' },
    TRIP: { r: 2, n: 'Tripadvisor, Inc.', s: 'consumo_discrecional' },
    TRVV: { r: 6, n: 'The Travelers Cos. Inc.', s: 'financiero' },
    TSLA: { r: 15, n: 'Tesla, Inc.', s: 'consumo_discrecional' },
    TSM: { r: 9, n: 'Taiwan Semiconductor Manufacturing', s: 'tecnologia' },
    TTE: { r: 3, n: 'TotalEnergies SE', s: 'energia' },
    TV: { r: 3, n: 'Grupo Televisa S.A.', s: 'comunicaciones' },
    TWLO: { r: 36, n: 'Twilio Inc', s: 'tecnologia' },
    TXN: { r: 5, n: 'Texas Instruments Inc', s: 'tecnologia' },
    TXR: { r: 4, n: 'Ternium S.A.', s: 'materiales' },
    UAL: { r: 5, n: 'United Airlines Holdings Inc.', s: 'industria' },
    UBER: { r: 2, n: 'Uber Technologies Inc.', s: 'tecnologia' },
    UGP: { r: 1, n: 'Ultrapar Participações S.A.', s: 'energia' },
    UL: { r: 3, n: 'Unilever PLC - Sponsored', s: 'consumo_basico' },
    UNH: { r: 33, n: 'UnitedHealth Group Inc.', s: 'salud' },
    UNP: { r: 20, n: 'Union Pacific Corp.', s: 'industria' },
    UPST: { r: 5, n: 'Upstart Hldgs Inc', s: 'financiero' },
    URA: { r: 5, n: 'Global X Uranium ETF', s: 'energia' },
    URBN: { r: 2, n: 'Urban Outfitters INC.', s: 'consumo_discrecional' },
    USB: { r: 5, n: 'U.S. Bancorp', s: 'financiero' },
    USO: { r: 15, n: 'United States Oil Fund', s: 'commodities' },
    V: { r: 18, n: 'Visa Inc', s: 'financiero' },
    VALE: { r: 2, n: 'Vale S.A.', s: 'materiales' },
    VALE3: { r: 1, n: 'Vale S.A.', s: 'materiales' },
    VEA: { r: 10, n: 'Vanguard FTSE Developed Markets ETF', s: 'indices' },
    VIG: { r: 39, n: 'VANGUARD DIVIDEND APPRECIATION', s: 'indices' },
    VIST: { r: 3, n: 'Vista Energy S.A.B. de C.V.', s: 'energia' },
    VIV: { r: 1, n: 'Telefônica Brasil S.A.', s: 'comunicaciones' },
    VIVT3: { r: 1, n: 'Telefônica Brasil S.A.', s: 'comunicaciones' },
    VOD: { r: 1, n: 'Vodafone Group Plc', s: 'comunicaciones' },
    VRSN: { r: 6, n: 'Verisign, Inc.', s: 'tecnologia' },
    VRTX: { r: 101, n: 'VERTEX PHARMACEUTICALS INC', s: 'salud' },
    VST: { r: 26, n: 'VISTRA CORPORATION', s: 'servicios_publicos' },
    VXX: { r: 5, n: 'iPath Series B S&P 500 VIX', s: 'indices' },
    VZ: { r: 4, n: 'Verizon Communications Inc.', s: 'comunicaciones' },
    WBO: { r: 6, n: 'Weibo Corporation', s: 'comunicaciones' },
    WDC: { r: 92, n: 'WESTERN DIGITAL CORP', s: 'tecnologia' },
    WEGE3: { r: 1, n: 'Weg S.A.', s: 'industria' },
    WELL: { r: 48, n: 'WELLTOWER INC', s: 'inmobiliario' },
    WFC: { r: 5, n: 'Wells Fargo & Co.', s: 'financiero' },
    WMT: { r: 18, n: 'Walmart Inc.', s: 'consumo_basico' },
    XLB: { r: 18, n: 'The Materials Select Sector SPDR Fund', s: 'materiales' },
    XLC: { r: 19, n: 'The Communication Services Select Sector SPDR Fund', s: 'comunicaciones' },
    XLE: { r: 2, n: 'ENERGY SELECT SECTOR SPDR FUND', s: 'energia' },
    XLF: { r: 2, n: 'FINANCIAL SELECT SECTOR SPDR FUND', s: 'financiero' },
    XLI: { r: 28, n: 'The Industrial Select Sector SPDR Fund', s: 'industria' },
    XLK: { r: 46, n: 'The Technology Select Sector SPDR Fund', s: 'tecnologia' },
    XLP: { r: 16, n: 'The Consumer Staples Select Sector SPDR Fund', s: 'consumo_basico' },
    XLRE: { r: 9, n: 'The Real Estate Select Sector SPDR Fund', s: 'inmobiliario' },
    XLU: { r: 15, n: 'Utilities Select Sector SPDR Fund', s: 'servicios_publicos' },
    XLV: { r: 29, n: 'The Health Care Select Sector SPDR Fund', s: 'salud' },
    XLY: { r: 43, n: 'The Consumer Discretionary Select Sector SPDR Fund', s: 'consumo_discrecional' },
    XME: { r: 30, n: 'State Street SPDR S&P Metals & Mining ETF', s: 'materiales' },
    XOM: { r: 10, n: 'Exxon Mobil Corporation', s: 'energia' },
    XP: { r: 4, n: 'XP Inc', s: 'financiero' },
    XPEV: { r: 4, n: 'XPENG INC', s: 'consumo_discrecional' },
    XROX: { r: 1, n: 'Xerox Holding Corporation', s: 'industria' },
    XYZ: { r: 20, n: 'Square Inc.', s: 'tecnologia' },
    YELP: { r: 2, n: 'Yelp Inc.', s: 'comunicaciones' },
    ZM: { r: 47, n: 'Zoom Video Communications Inc.', s: 'tecnologia' },
  }
};
