/* ==========================================================================
   SISTEMA 4K — el reglamento, embebido en anamnesis
   --------------------------------------------------------------------------
   Es el mismo documento que vive como artefacto, empaquetado como módulo para
   poder consultarlo sin salir del dashboard. Va como string y no como iframe
   ni fetch a propósito: el dashboard se abre muchas veces desde file://, donde
   fetch() de un archivo vecino falla por CORS y el iframe queda a merced de la
   política del navegador. Un <script> siempre carga.

   La paleta original del documento era fría (azul pizarra). Acá se remapea
   sobre los tokens de anamnesis, así el modal sigue el tema del dashboard —
   claro y oscuro — sin una sola regla de tema propia. Las fuentes también se
   remapean: el reglamento tiene que leerse como una sección más de la app y
   no como una página ajena incrustada.
   ========================================================================== */
(function () {
  'use strict';

  var CSS = [
'.s4k{',
'  --ground: var(--bg-1);',
'  --surface: var(--card);',
'  --surface-2: var(--bg-2);',
'  --line: var(--border);',
'  --line-soft: color-mix(in srgb, var(--border) 65%, transparent);',
'  --s-ink: var(--ink);',
'  --s-ink-2: var(--ink-2);',
'  --s-muted: var(--muted);',
'  --acc: var(--inv-accent, var(--accent));',
'  --acc-soft: color-mix(in srgb, var(--accent) 14%, transparent);',
'  --crit: var(--red);',
'  --crit-soft: color-mix(in srgb, var(--red) 13%, transparent);',
'  --warn: #9A6B12;',
'  --warn-soft: color-mix(in srgb, #9A6B12 15%, transparent);',
'  --s-shadow: 0 1px 2px rgba(0,0,0,.05), 0 10px 28px -18px rgba(0,0,0,.24);',
'  color: var(--s-ink);',
'  font-family: "Inter", system-ui, sans-serif;',
'  font-size: 14px;',
'  line-height: 1.6;',
'}',
'[data-theme="dark"] .s4k{ --warn:#D2A044; --s-shadow:0 1px 2px rgba(0,0,0,.45), 0 10px 28px -18px rgba(0,0,0,.65); }',
'.s4k *{ box-sizing: border-box; }',
'.s4k-doc{ display:flex; flex-direction:column; gap:22px; }',
'',
'.s4k h1, .s4k h2, .s4k h3{ font-family:"Fraunces", Georgia, serif; margin:0; text-wrap:balance; letter-spacing:.005em; }',
'.s4k h1{ font-size:31px; font-weight:600; line-height:1.08; }',
'.s4k h2{ font-size:20px; font-weight:600; line-height:1.2; }',
'.s4k h3{ font-size:15px; font-weight:600; margin-top:4px; }',
'.s4k p{ margin:0; }',
'.s4k .mono{ font-family:"JetBrains Mono", ui-monospace, monospace; font-variant-numeric:tabular-nums; }',
'.s4k .eyebrow{ font-family:"JetBrains Mono", monospace; font-size:10px; letter-spacing:.16em;',
'  text-transform:uppercase; color:var(--acc); font-weight:500; }',
'',
'.s4k header{ border-bottom:2px solid var(--s-ink); padding-bottom:14px; display:flex; flex-direction:column; gap:6px; }',
'.s4k header .sub{ color:var(--s-muted); font-size:14px; max-width:62ch; }',
'.s4k section{ display:flex; flex-direction:column; gap:11px; }',
'.s4k .lede{ font-size:14px; color:var(--s-ink-2); max-width:74ch; line-height:1.55; }',
'',
'.s4k .figs{ display:grid; grid-template-columns:repeat(auto-fit,minmax(148px,1fr)); gap:1px;',
'  background:var(--line-soft); border:1px solid var(--line-soft); border-radius:4px; overflow:hidden; }',
'.s4k .fig{ background:var(--surface); padding:10px 13px; display:flex; flex-direction:column; gap:2px; }',
'.s4k .fig .k{ font-family:"JetBrains Mono", monospace; font-size:9.5px; letter-spacing:.09em;',
'  text-transform:uppercase; color:var(--s-muted); }',
'.s4k .fig .v{ font-family:"JetBrains Mono", monospace; font-variant-numeric:tabular-nums;',
'  font-size:19px; font-weight:500; line-height:1.15; }',
'.s4k .fig .n{ font-size:11px; color:var(--s-muted); }',
'.s4k .v.crit{ color:var(--crit); } .s4k .v.acc{ color:var(--acc); } .s4k .v.warn{ color:var(--warn); }',
'',
'.s4k .gates{ display:flex; flex-direction:column; gap:7px; counter-reset:g; }',
'.s4k .gate{ background:var(--surface); border:1px solid var(--line); border-radius:4px;',
'  padding:11px 14px 12px 48px; position:relative; box-shadow:var(--s-shadow); }',
'.s4k .gate::before{ counter-increment:g; content:counter(g);',
'  position:absolute; left:13px; top:12px; width:23px; height:23px; border-radius:3px;',
'  background:var(--acc); color:var(--on-dark-text, #fff);',
'  font-family:"JetBrains Mono", monospace; font-size:12px; font-weight:700;',
'  display:flex; align-items:center; justify-content:center; }',
'.s4k .gate h3{ margin:0 0 3px; }',
'.s4k .gate p{ font-size:13.5px; color:var(--s-ink-2); line-height:1.5; }',
'.s4k .gate .rule{ font-family:"JetBrains Mono", monospace; font-size:12px; background:var(--surface-2);',
'  padding:5px 9px; border-radius:3px; margin-top:7px; display:block; overflow-x:auto; white-space:nowrap; }',
'',
'.s4k .tw{ overflow-x:auto; border:1px solid var(--line); border-radius:4px; background:var(--surface); }',
'.s4k table{ border-collapse:collapse; width:100%; font-size:12.5px; min-width:460px; }',
'.s4k th{ font-family:"JetBrains Mono", monospace; font-size:9.5px; letter-spacing:.08em; text-transform:uppercase;',
'  color:var(--s-muted); font-weight:500; text-align:right; padding:7px 10px;',
'  background:var(--surface-2); border-bottom:1px solid var(--line); white-space:nowrap; }',
'.s4k th:first-child{ text-align:left; }',
'.s4k td{ padding:6px 10px; border-bottom:1px solid var(--line-soft); text-align:right;',
'  font-family:"JetBrains Mono", monospace; font-variant-numeric:tabular-nums; white-space:nowrap; color:var(--s-ink-2); }',
'.s4k td:first-child{ text-align:left; font-family:"Inter", sans-serif; }',
'.s4k tbody tr:last-child td{ border-bottom:none; }',
'.s4k tr.mark td{ background:var(--acc-soft); font-weight:700; color:var(--s-ink); }',
'.s4k tr.bad td{ background:var(--crit-soft); }',
'.s4k .pos{ color:var(--acc); } .s4k .neg{ color:var(--crit); }',
'',
'.s4k .note{ border-left:3px solid var(--acc); background:var(--surface);',
'  padding:11px 14px; border-radius:0 4px 4px 0; font-size:13.5px; line-height:1.55; color:var(--s-ink-2); box-shadow:var(--s-shadow); }',
'.s4k .note.stop{ border-left-color:var(--crit); }',
'.s4k .note.warn{ border-left-color:var(--warn); }',
'.s4k .note strong{ color:var(--s-ink); }',
'',
'.s4k .routine{ display:flex; flex-direction:column; border:1px solid var(--line);',
'  border-radius:4px; overflow:hidden; background:var(--surface); }',
'.s4k .step{ display:grid; grid-template-columns:80px 1fr; gap:13px; padding:9px 14px;',
'  border-bottom:1px solid var(--line-soft); }',
'.s4k .step:last-child{ border-bottom:none; }',
'.s4k .step .t{ font-family:"JetBrains Mono", monospace; font-size:11.5px; color:var(--acc); font-weight:500; }',
'.s4k .step .d{ font-size:13.5px; color:var(--s-ink-2); line-height:1.5; }',
'.s4k .step .d b{ color:var(--s-ink); }',
'',
'.s4k ul{ margin:0; padding-left:18px; display:flex; flex-direction:column; gap:5px; font-size:13.5px; line-height:1.5; color:var(--s-ink-2); }',
'.s4k li::marker{ color:var(--acc); }',
'.s4k code{ font-family:"JetBrains Mono", monospace; font-size:12px; background:var(--surface-2); padding:1px 5px; border-radius:3px; }',
'.s4k strong{ color:var(--s-ink); }',
'',
'.s4k footer{ border-top:1px solid var(--line); padding-top:14px; color:var(--s-muted); font-size:12px; line-height:1.5;',
'  display:flex; flex-direction:column; gap:8px; }',
'',
'/* ---- cadena de derivación ---- */',
'.s4k .chain{ list-style:none; margin:0; padding:0; counter-reset:c; background:var(--surface);',
'  border:1px solid var(--line); border-radius:4px; overflow:hidden; box-shadow:var(--s-shadow); }',
'.s4k .chain li{ counter-increment:c; display:grid; grid-template-columns:20px 1fr auto auto;',
'  gap:5px 13px; align-items:baseline; padding:8px 13px; border-bottom:1px solid var(--line-soft); }',
'.s4k .chain li:last-child{ border-bottom:none; }',
'.s4k .chain li::before{ content:counter(c); font-family:"JetBrains Mono", monospace;',
'  font-size:10.5px; font-weight:700; color:var(--acc); }',
'.s4k .chain .q{ font-size:13.5px; color:var(--s-ink-2); }',
'.s4k .chain .f{ font-size:12px; color:var(--s-muted); white-space:nowrap; }',
'.s4k .chain .r{ font-size:16px; font-weight:700; white-space:nowrap; text-align:right; min-width:72px; color:var(--s-ink); }',
'.s4k .chain .r.crit{ color:var(--crit); }',
'.s4k .chain sup{ font-size:.68em; }',
'',
'/* ---- acordeón con línea de progreso ----',
'   Cada sección es un nodo de una línea vertical. Vienen todas cerradas: el',
'   reglamento entero de una sola vez es un muro, y lo que uno necesita a las',
'   14:55 es una sola de las ocho secciones. El punto y el tramo de línea se',
'   pintan al abrir, así el índice también funciona como marca de lectura. */',
'.s4k-flow{ display:flex; flex-direction:column; margin-top:4px; }',
'.s4k-node{ display:grid; grid-template-columns:26px 1fr; column-gap:12px; }',
'.s4k-rail{ display:flex; flex-direction:column; align-items:center; }',
'.s4k-dot{',
'  width:23px; height:23px; border-radius:50%; flex-shrink:0;',
'  border:2px solid var(--line); background:var(--surface); color:var(--s-muted);',
'  font-family:"JetBrains Mono", monospace; font-size:11px; font-weight:700; line-height:1;',
'  display:flex; align-items:center; justify-content:center;',
'  transition:background .16s, border-color .16s, color .16s;',
'}',
'.s4k-line{ flex:1 1 auto; width:2px; background:var(--line); margin:2px 0; border-radius:1px;',
'  transition:background .16s; }',
'.s4k-node:last-child .s4k-line{ visibility:hidden; }',
'.s4k-node.on .s4k-dot{ background:var(--acc); border-color:var(--acc); color:var(--on-dark-text, #fff); }',
'.s4k-node.on .s4k-line{ background:var(--acc); }',
'',
'.s4k-sec{ border:1px solid var(--line); border-radius:5px; background:var(--surface);',
'  margin-bottom:7px; box-shadow:var(--s-shadow); }',
'.s4k-sec > summary{',
'  list-style:none; cursor:pointer; padding:9px 13px;',
'  display:flex; align-items:center; gap:12px;',
'  border-radius:4px;',
'}',
'.s4k-sec > summary::-webkit-details-marker{ display:none; }',
'.s4k-sec > summary:hover{ background:var(--surface-2); }',
'.s4k-sec > summary:focus-visible{ outline:2px solid var(--acc); outline-offset:-2px; }',
'.s4k-sum-txt{ display:flex; flex-direction:column; gap:2px; min-width:0; flex:1; }',
'.s4k-sum-t{ font-family:"Fraunces", Georgia, serif; font-size:15.5px; font-weight:600; color:var(--s-ink); line-height:1.25; }',
'.s4k-sum-d{ font-size:12px; color:var(--s-muted); line-height:1.4; }',
'.s4k-chev{ flex-shrink:0; width:9px; height:9px; margin-right:3px;',
'  border-right:2px solid var(--s-muted); border-bottom:2px solid var(--s-muted);',
'  transform:rotate(45deg); transition:transform .16s; }',
'.s4k-sec[open] > summary .s4k-chev{ transform:rotate(-135deg); }',
'.s4k-sec[open] > summary{ border-bottom:1px solid var(--line-soft); border-radius:4px 4px 0 0; }',
'.s4k-sec[open] > summary .s4k-sum-d{ display:none; }',
'.s4k-body{ padding:13px 14px 15px; }',
'',
'@media (max-width:560px){ .s4k h1{ font-size:30px; } .s4k .step{ grid-template-columns:1fr; gap:4px; }',
'  .s4k-node{ grid-template-columns:24px 1fr; column-gap:10px; }',
'  .s4k-dot{ width:22px; height:22px; font-size:10px; }',
'  .s4k-sum-t{ font-size:14.5px; }',
'  .s4k .chain li{ grid-template-columns:20px 1fr; }',
'  .s4k .chain .f, .s4k .chain .r{ grid-column:2; text-align:left; } }'
  ].join('\n');

  var HTML = [
    "<header>",
    "  <p class=\"eyebrow\">Sistema de trading · Futuros perpetuos</p>",
    "  <h1>Sistema 4K</h1>",
    "  <p class=\"sub\">Reglas de ejecución para llevar una cuenta de 400 USDT hasta una renta de 4.000 al mes. Diseñado desde el objetivo hacia atrás.</p>",
    "</header>",
    "",
    "<!-- ===================== EL OBJETIVO ===================== -->",
    "<section>",
    "  <h2>El objetivo, traducido a números</h2>",
    "  <p class=\"lede\">Ganar 4.000 al mes con 400 de capital significa terminar el mes con 4.400: multiplicar la cuenta por 11. Cripto no cierra los fines de semana, así que el mes son <strong>30 ruedas</strong>, no 22.</p>",
    "",
    "  <ol class=\"chain\">",
    "    <li>",
    "      <span class=\"q\">Cuánto hay que multiplicar el capital</span>",
    "      <span class=\"f mono\">4.400 ÷ 400</span>",
    "      <span class=\"r mono\">×11</span>",
    "    </li>",
    "    <li>",
    "      <span class=\"q\">Cuánto por día, compuesto en 30 ruedas</span>",
    "      <span class=\"f mono\">11 <sup>1/30</sup> − 1</span>",
    "      <span class=\"r mono crit\">8,32%</span>",
    "    </li>",
    "    <li>",
    "      <span class=\"q\">Cuánto rinde una operación, en promedio</span>",
    "      <span class=\"f mono\">45%×2R − 55%×1R</span>",
    "      <span class=\"r mono\">+0,35R</span>",
    "    </li>",
    "    <li>",
    "      <span class=\"q\">Cuánto hay que arriesgar por operación</span>",
    "      <span class=\"f mono\">8,32% ÷ 0,35</span>",
    "      <span class=\"r mono crit\">23,8%</span>",
    "    </li>",
    "  </ol>",
    "",
    "  <div class=\"note\">",
    "    <strong>Los dos pasos que hacen ruido.</strong> El segundo es interés compuesto al revés: si cada día multiplicás por el mismo factor y en 30 días querés llegar a ×11, ese factor es la raíz 30 de 11 — 1,0832, o sea 8,32% diario. No es 1.000% ÷ 30 = 33% diario, porque cada día crece sobre lo que dejó el anterior. El cuarto traduce ese 8,32% a riesgo: si una operación te devuelve en promedio 0,35 veces lo que arriesgaste, para que te devuelva 8,32% tenés que arriesgar 8,32 ÷ 0,35 = 23,8% de la cuenta. <em>Cada día.</em>",
    "  </div>",
    "",
    "  <div class=\"figs\">",
    "    <div class=\"fig\"><span class=\"k\">Diario compuesto</span><span class=\"v crit\">8,32%</span><span class=\"n\">los 30 días</span></div>",
    "    <div class=\"fig\"><span class=\"k\">Mensual</span><span class=\"v crit\">1.000%</span><span class=\"n\">400 → 4.400</span></div>",
    "    <div class=\"fig\"><span class=\"k\">Riesgo necesario</span><span class=\"v crit\">23,8%</span><span class=\"n\">por operación</span></div>",
    "    <div class=\"fig\"><span class=\"k\">Riesgo óptimo</span><span class=\"v acc\">17,5%</span><span class=\"n\">criterio de Kelly</span></div>",
    "  </div>",
    "",
    "  <h3>Un mes, simulado 400.000 veces</h3>",
    "  <p class=\"lede\">Mismo sistema (45% de aciertos, R:R 2), 30 operaciones, cambiando solo cuánto se arriesga por operación. <span class=\"mono\">p10</span> es el resultado del 10% peor de los meses; <span class=\"mono\">p90</span>, el del 10% mejor.</p>",
    "",
    "  <div class=\"tw\">",
    "    <table>",
    "      <thead><tr><th>Riesgo</th><th>Termina bajo 40</th><th>p10</th><th>Mediana</th><th>p90</th><th>Llega a 4.400</th></tr></thead>",
    "      <tbody>",
    "        <tr class=\"mark\"><td>2% — el del sistema</td><td>0,0%</td><td>395</td><td>472</td><td>599</td><td>0,0%</td></tr>",
    "        <tr><td>5%</td><td>0,0%</td><td>372</td><td>577</td><td>1.038</td><td>0,0%</td></tr>",
    "        <tr><td>10%</td><td>0,0%</td><td>301</td><td>714</td><td>2.256</td><td class=\"pos\">1,4%</td></tr>",
    "        <tr><td>17,5% — Kelly</td><td class=\"neg\">1,2%</td><td>172</td><td>752</td><td>5.391</td><td class=\"pos\">13,5%</td></tr>",
    "        <tr class=\"bad\"><td>23,8% — el necesario</td><td class=\"neg\">3,1%</td><td class=\"neg\">86</td><td>621</td><td>8.749</td><td class=\"pos\">23,1%</td></tr>",
    "      </tbody>",
    "    </table>",
    "  </div>",
    "",
    "  <div class=\"note warn\">",
    "    <strong>El objetivo no es imposible en un mes: es improbable y caro.</strong> Con 23,8% de riesgo llegás a los 4.400 en <strong>23 de cada 100 meses</strong>. El precio es la columna p10: uno de cada diez meses terminás con 86 USDT, y la mediana (621) es peor que la de arriesgar 17,5%. Ese es el hallazgo que define el diseño — <strong>la mediana deja de mejorar en 17,5% y empieza a caer</strong>. Arriesgar más de ahí compra cola derecha pagando con el centro de la distribución.",
    "  </div>",
    "",
    "  <h3>Un año, que es donde se decide</h3>",
    "  <p class=\"lede\">Un mes bueno no prueba nada. Esto es lo mismo repetido 12 veces — 360 operaciones — mirando cuántas veces la cuenta pasa por debajo de 40 USDT <em>en algún momento</em> del año.</p>",
    "",
    "  <div class=\"tw\">",
    "    <table>",
    "      <thead><tr><th>Riesgo</th><th>Crece por operación</th><th>Toca fondo alguna vez</th><th>p10 al año</th></tr></thead>",
    "      <tbody>",
    "        <tr class=\"mark\"><td>2%</td><td class=\"pos\">+0,65%</td><td>0,0%</td><td>2.063</td></tr>",
    "        <tr><td>5%</td><td class=\"pos\">+1,47%</td><td>0,0%</td><td>13.581</td></tr>",
    "        <tr><td>10%</td><td class=\"pos\">+2,41%</td><td>0,3%</td><td>74.161</td></tr>",
    "        <tr><td>17,5% — Kelly</td><td class=\"pos\">+2,92%</td><td class=\"neg\">9,0%</td><td>40.500</td></tr>",
    "        <tr class=\"bad\"><td>23,8% — el necesario</td><td class=\"pos\">+2,57%</td><td class=\"neg\">30,0%</td><td>1.498</td></tr>",
    "        <tr class=\"bad\"><td>30%</td><td>+1,53%</td><td class=\"neg\">57,0%</td><td>5</td></tr>",
    "        <tr class=\"bad\"><td>35%</td><td>+0,19%</td><td class=\"neg\">76,4%</td><td>0</td></tr>",
    "      </tbody>",
    "    </table>",
    "  </div>",
    "",
    "  <div class=\"note stop\">",
    "    <strong>Leé esta tabla por la tercera columna, no por la cuarta.</strong> Los p10 de millones son ficción del modelo: supone que el 45% de aciertos se sostiene 360 veces seguidas y que el mercado absorbe cualquier tamaño. Ninguna de las dos cosas es cierta. Lo que sí resiste el modelo es la comparación relativa: <strong>arriesgar 23,8% te lleva a estar prácticamente fundido una vez de cada tres años; arriesgar 2%, nunca.</strong> Y la columna del crecimiento muestra por qué pasar de Kelly no compensa: entre 17,5% y 23,8% el crecimiento por operación <em>baja</em>, mientras la chance de fundirse se triplica.",
    "  </div>",
    "",
    "  <p class=\"lede\">Por eso el sistema opera con <strong>2%</strong>. No porque 23,8% sea imposible, sino porque la forma de llegar a 4.000 al mes no es arriesgar más por operación: es que la cuenta crezca hasta que el mismo 2% valga esa cifra. Eso está en la última sección.</p>",
    "</section>",
    "",
    "<!-- ===================== EL SISTEMA ===================== -->",
    "<section>",
    "  <h2>Las cinco compuertas</h2>",
    "  <p class=\"lede\">Un trade existe solo si pasa las cinco. Si falla una, no hay operación — y no operar es una decisión válida del sistema, no una oportunidad perdida.</p>",
    "",
    "  <div class=\"gates\">",
    "    <div class=\"gate\">",
    "      <h3>Tendencia establecida</h3>",
    "      <p>En las últimas 10 velas de 4h, el precio estuvo a más de 1,5 ATR de su EMA20. Long si está por encima, short si está por debajo. Sin esto no hay dirección, solo ruido.</p>",
    "      <span class=\"rule\">|precio − EMA20| &gt; 1,5 × ATR(14) en algún punto de las últimas 10 velas</span>",
    "    </div>",
    "",
    "    <div class=\"gate\">",
    "      <h3>Retroceso a la media</h3>",
    "      <p>El precio volvió a menos de 0,5 ATR de la EMA20. Es el único momento de entrada: comprás donde el impulso descansó, no donde se estiró.</p>",
    "      <span class=\"rule\">|precio − EMA20| &lt; 0,5 × ATR(14)</span>",
    "    </div>",
    "",
    "    <div class=\"gate\">",
    "      <h3>El volumen no contradice</h3>",
    "      <p>La última vela cerrada tiene menos de 2× el volumen medio de 20. Un retroceso con volumen alto no es descanso: es vendedor real, y el nivel probablemente ceda.</p>",
    "      <span class=\"rule\">volumen última vela &lt; 2 × media(20)</span>",
    "    </div>",
    "",
    "    <div class=\"gate\">",
    "      <h3>El stop cae fuera de la liquidez</h3>",
    "      <p>Base de 1,5 ATR, corrido hasta quedar por debajo del mínimo visible más cercano. Un stop pegado a un mínimo obvio es liquidez que alguien va a buscar.</p>",
    "      <span class=\"rule\">stop = min(entrada − 1,5×ATR ; mínimo estructural × 0,995)</span>",
    "    </div>",
    "",
    "    <div class=\"gate\">",
    "      <h3>R:R igual o mayor a 2</h3>",
    "      <p>El objetivo está al menos al doble de distancia que el stop, en un nivel que el precio ya visitó o que la estructura justifica. Si no llega a 2, se descarta el trade — nunca se acerca el stop para forzar el número.</p>",
    "      <span class=\"rule\">(objetivo − entrada) ÷ (entrada − stop) ≥ 2,00</span>",
    "    </div>",
    "  </div>",
    "</section>",
    "",
    "<!-- ===================== TAMAÑO ===================== -->",
    "<section>",
    "  <h2>Tamaño y apalancamiento</h2>",
    "  <p class=\"lede\">El tamaño no se elige: se despeja. Y el apalancamiento no es una palanca de ganancia, es lo que decide dónde cae la liquidación.</p>",
    "",
    "  <div class=\"figs\">",
    "    <div class=\"fig\"><span class=\"k\">Riesgo por operación</span><span class=\"v acc\">2%</span><span class=\"n\">del capital, siempre</span></div>",
    "    <div class=\"fig\"><span class=\"k\">Unidades</span><span class=\"v\">R ÷ d</span><span class=\"n\">riesgo ÷ distancia al stop</span></div>",
    "    <div class=\"fig\"><span class=\"k\">Colchón mínimo</span><span class=\"v acc\">3×</span><span class=\"n\">liquidación vs stop</span></div>",
    "  </div>",
    "",
    "  <ul>",
    "    <li><strong>Unidades</strong> = <code>(capital × 0,02) ÷ (entrada − stop)</code></li>",
    "    <li><strong>Apalancamiento</strong>: el más bajo que deje la liquidación a tres veces la distancia del stop. Nunca por encima del máximo del tramo del exchange.</li>",
    "    <li><strong>Margen extra</strong>: solo el necesario para llegar a ese colchón. Más allá de eso es capital inmovilizado que no protege nada — con el stop puesto, la pérdida es la misma.</li>",
    "    <li><strong>Costos</strong>: verificá que comisiones más funding estimado no superen el 5% de la ganancia objetivo. Si lo superan, el nocional es muy grande para el objetivo.</li>",
    "  </ul>",
    "",
    "  <div class=\"note warn\">",
    "    <strong>La liquidación no es simétrica con el stop.</strong> Tu stop es una orden que se manda al mercado y puede llenarse peor. La liquidación la ejecuta el exchange, es automática y es final. El colchón de 3× no es para el día normal: es para el hueco, el deslizamiento y la vela violenta, que es donde están las pérdidas grandes.",
    "  </div>",
    "</section>",
    "",
    "<!-- ===================== SALIDAS ===================== -->",
    "<section>",
    "  <h2>Las tres salidas del lado perdedor</h2>",
    "  <p class=\"lede\">Cinco condiciones para entrar y tres objetivos escalonados para cobrar dejan una asimetría: todo el plan está escrito para el escenario bueno. Estas tres reglas la cierran. Se dispara la primera que se cumple — no se evalúan, no se comparan.</p>",
    "",
    "  <div class=\"tw\">",
    "    <table>",
    "      <thead><tr><th>Regla</th><th>Se dispara cuando</th><th>Qué cubre</th></tr></thead>",
    "      <tbody>",
    "        <tr><td>Estructura</td><td>Pierde el mínimo del último impulso con volumen &gt; 2× la media</td><td>La tendencia se rompió</td></tr>",
    "        <tr><td>Precio</td><td>Cierre de 4h por debajo de la zona de ruptura que originó el movimiento</td><td>Respaldo duro</td></tr>",
    "        <tr class=\"mark\"><td>Tiempo</td><td>Pasaron 5 días sin tocar el primer objetivo</td><td>El capital dejó de trabajar</td></tr>",
    "      </tbody>",
    "    </table>",
    "  </div>",
    "",
    "  <p class=\"lede\"><strong>La de estructura llega primero y es la más fina</strong>, porque exige volumen: no salta por una deriva tranquila, solo cuando aparece vendedor real. La de precio es el respaldo por si la estructura no alcanzó a confirmarse. La de tiempo es independiente de las otras dos y se dispara aunque el precio esté quieto.</p>",
    "",
    "  <h3 style=\"margin-top:12px\">Por qué cinco días</h3>",
    "  <p class=\"lede\">No es un número redondo elegido a gusto: sale de medir cuánto tardó el activo en recuperarse de sus últimas cinco correcciones.</p>",
    "",
    "  <div class=\"tw\">",
    "    <table>",
    "      <thead><tr><th>Corrección desde máximo local</th><th>Profundidad</th><th>Velas de 4h hasta recuperar</th><th>Días</th></tr></thead>",
    "      <tbody>",
    "        <tr><td>Pico 1</td><td>−6,48%</td><td>7</td><td>1,2</td></tr>",
    "        <tr><td>Pico 2</td><td>−11,22%</td><td>19</td><td>3,2</td></tr>",
    "        <tr><td>Pico 3</td><td>−7,79%</td><td>9</td><td>1,5</td></tr>",
    "        <tr><td>Pico 4</td><td>−9,10%</td><td>10</td><td>1,7</td></tr>",
    "        <tr><td>Pico 5</td><td>−6,30%</td><td>4</td><td>0,7</td></tr>",
    "      </tbody>",
    "    </table>",
    "  </div>",
    "",
    "  <p class=\"lede\">La más lenta tardó <span class=\"mono\">3,2 días</span>. Cinco cubre todas con margen: si a esa altura no recuperó, ya no es el patrón que compraste. <strong>Cada activo tiene su propio número</strong> — se recalcula igual, midiendo sus últimas cinco correcciones.</p>",
    "",
    "  <div class=\"note\">",
    "    <strong>El funding casi nunca es la razón para salir.</strong> Sobre un nocional de 500 USDT, una tasa del 23% anual cuesta 0,32 al día: tardaría 203 días en igualar lo que cuesta cerrar una posición un 13% abajo. Lo que sí pesa es la capacidad bloqueada — un mes de garantía inmovilizada cuesta unos 9 de funding y del orden de 86 en operaciones que no pudiste tomar al tamaño correcto. El costo visible es el chico.",
    "  </div>",
    "",
    "  <div class=\"note warn\">",
    "    <strong>El trade que aguantás no es el trade que abriste.</strong> Una entrada técnica con objetivos al 6% tiene un horizonte de días. Si se sostiene treinta, se convirtió en una inversión que nunca decidiste hacer — la decisión la tomó el mercado por omisión. Aguantar es una estrategia legítima, pero es otra, con otro tamaño y otra tesis. Lo que no se puede es empezar una y terminar en la otra sin haberlo elegido.",
    "  </div>",
    "</section>",
    "",
    "<!-- ===================== LÍMITES ===================== -->",
    "<section>",
    "  <h2>Límites que cortan el día</h2>",
    "  <p class=\"lede\">Sin estos, una racha mala se convierte en una decisión mala. Son automáticos: no se evalúan, se obedecen.</p>",
    "",
    "  <div class=\"tw\">",
    "    <table>",
    "      <thead><tr><th>Límite</th><th>Umbral</th><th>Qué pasa</th></tr></thead>",
    "      <tbody>",
    "        <tr><td>Posiciones abiertas</td><td>3</td><td>No se abre una cuarta</td></tr>",
    "        <tr><td>Riesgo total simultáneo</td><td>6%</td><td>Suma de los stops abiertos</td></tr>",
    "        <tr class=\"mark\"><td>Pérdida en el día</td><td class=\"neg\">−4%</td><td>Se cierra la plataforma hasta mañana</td></tr>",
    "        <tr class=\"mark\"><td>Pérdida en la semana</td><td class=\"neg\">−8%</td><td>Se para hasta el lunes</td></tr>",
    "        <tr><td>Operaciones correlacionadas</td><td>2</td><td>Máximo dos del mismo bloque</td></tr>",
    "      </tbody>",
    "    </table>",
    "  </div>",
    "",
    "  <div class=\"note stop\">",
    "    <strong>Prohibiciones absolutas.</strong> No se mueve un stop en contra. No se agrega margen a una posición perdedora. No se entra sin stop cargado junto con la orden. No se opera fuera de las cinco compuertas por corazonada. Cada una de estas tiene una operación real detrás que salió cara.",
    "  </div>",
    "</section>",
    "",
    "<!-- ===================== RUTINA ===================== -->",
    "<section>",
    "  <h2>La rutina diaria</h2>",
    "  <p class=\"lede\">Cuarenta minutos por día, en dos bloques. El sistema no exige mirar pantallas: exige ejecutar un procedimiento.</p>",
    "",
    "  <div class=\"routine\">",
    "    <div class=\"step\"><span class=\"t\">07:00</span><span class=\"d\"><b>Barrido.</b> Los 7 activos en 4h. Anotá cuáles están a más de 1,5 ATR de su EMA20 y en qué dirección. Esos son los candidatos del día.</span></div>",
    "    <div class=\"step\"><span class=\"t\">07:20</span><span class=\"d\"><b>Alertas.</b> Cargá en TradingView el nivel de entrada de cada candidato: <code>EMA20 + 0,5 ATR</code>. Una alerta por activo, ni una más.</span></div>",
    "    <div class=\"step\"><span class=\"t\">Al saltar</span><span class=\"d\"><b>Verificación.</b> Las cinco compuertas, en orden. Si pasan, dimensionás en la mesa y cargás entrada, stop y objetivo juntos, en OCO.</span></div>",
    "    <div class=\"step\"><span class=\"t\">21:00</span><span class=\"d\"><b>Cierre.</b> Registrá lo que se ejecutó con su R. Anotá en una línea por qué entraste. Actualizá las alertas para mañana.</span></div>",
    "    <div class=\"step\"><span class=\"t\">Domingo</span><span class=\"d\"><b>Revisión.</b> Métricas de la semana. Recalculá los niveles de los 7. Si hubo alguna operación fuera de las reglas, escribí qué la disparó.</span></div>",
    "  </div>",
    "</section>",
    "",
    "<!-- ===================== MÉTRICAS ===================== -->",
    "<section>",
    "  <h2>Los cinco números</h2>",
    "  <p class=\"lede\">Se revisan el domingo. Ninguno individualmente decide nada; los cinco juntos dicen si el sistema funciona.</p>",
    "",
    "  <div class=\"tw\">",
    "    <table>",
    "      <thead><tr><th>Métrica</th><th>Cómo se calcula</th><th>Objetivo</th></tr></thead>",
    "      <tbody>",
    "        <tr><td>Expectancy</td><td>(WR × gan. media) − ((1−WR) × pérd. media)</td><td class=\"pos\">&gt; 0</td></tr>",
    "        <tr><td>R acumulado</td><td>Suma de los R de operaciones cerradas</td><td class=\"pos\">creciente</td></tr>",
    "        <tr><td>Profit factor</td><td>Ganancias ÷ pérdidas</td><td class=\"pos\">&gt; 1,5</td></tr>",
    "        <tr><td>Máximo drawdown</td><td>Mayor caída desde un pico de capital</td><td>&lt; 15%</td></tr>",
    "        <tr class=\"mark\"><td>Adherencia</td><td>Operaciones según reglas ÷ total</td><td class=\"pos\">100%</td></tr>",
    "      </tbody>",
    "    </table>",
    "  </div>",
    "",
    "  <div class=\"note\">",
    "    <strong>La adherencia es la única que se mide sobre vos y no sobre el mercado.</strong> Un sistema con expectativa positiva ejecutado al 70% no produce el 70% del resultado: produce cualquier cosa, porque el 30% que rompiste son justo las operaciones que tomaste con más carga emocional. Si algún número tiene que dar perfecto, es este.",
    "  </div>",
    "</section>",
    "",
    "<!-- ===================== EL CAMINO ===================== -->",
    "<section>",
    "  <h2>El camino a los 4.000</h2>",
    "  <p class=\"lede\">Con 2% de riesgo, R:R 2 y 45% de aciertos, la expectativa es de +0,35R por operación. Lo que cambia el plazo no es el riesgo — es cuántas operaciones válidas encontrás por día. La cuarta columna es el capital con el que ese rendimiento mensual ya vale 4.000 USDT.</p>",
    "",
    "  <div class=\"tw\">",
    "    <table>",
    "      <thead><tr><th>Operaciones por día</th><th>Rendimiento mensual</th><th>Capital al mes 6</th><th>Capital que hace falta</th><th>Llega a 4.000/mes</th></tr></thead>",
    "      <tbody>",
    "        <tr><td>1</td><td>21,7%</td><td>1.298</td><td>18.459</td><td>mes 20</td></tr>",
    "        <tr><td>2</td><td>48,0%</td><td>4.209</td><td>8.327</td><td>mes 8</td></tr>",
    "        <tr class=\"mark\"><td>3</td><td>80,1%</td><td>13.655</td><td>4.993</td><td class=\"pos\">mes 5</td></tr>",
    "      </tbody>",
    "    </table>",
    "  </div>",
    "",
    "  <p class=\"lede\">Con tres operaciones diarias la cuenta llega a ~5.000 en el mes 5, y desde ahí el 80,1% mensual produce los 4.000 sin cambiar una sola regla. <strong>El objetivo no se alcanza apostando más fuerte: se alcanza cuando la cuenta es lo bastante grande para que el mismo 2% valga esa cifra.</strong></p>",
    "",
    "  <div class=\"note\">",
    "    <strong>Las dos palancas legítimas para acelerar.</strong> Primera: más activos vigilados, que produce más operaciones válidas por día sin tocar el riesgo — es la diferencia entre el mes 27 y el mes 7. Segunda: depositar capital, que mueve el punto de partida directamente. Subir el riesgo por operación no es una tercera palanca; la simulación de arriba muestra que empeora incluso el resultado mediano.",
    "  </div>",
    "",
    "  <h3 style=\"margin-top:14px\">Cuándo subir el riesgo</h3>",
    "  <ul>",
    "    <li>Después de <strong>30 operaciones cerradas</strong> con expectancy positiva y adherencia del 100%, el riesgo puede pasar de 2% a 2,5%.</li>",
    "    <li>Después de <strong>60 operaciones</strong> en las mismas condiciones, a 3%. Ese es el techo.</li>",
    "    <li>Ante un drawdown superior al 15%, el riesgo vuelve a 1% hasta recuperar el pico anterior.</li>",
    "    <li>Nunca se sube el riesgo después de una racha ganadora sin las operaciones mínimas cumplidas. La racha no es evidencia; la muestra sí.</li>",
    "  </ul>",
    "</section>",
    "",
    "<footer>",
    "  <p><strong>Los supuestos de este plan:</strong> 45% de aciertos, R:R 2,0 y 30 ruedas por mes. Son razonables para un sistema de retroceso en tendencia, pero son supuestos — y el de 30 ruedas es el más frágil: el calendario permite operar los 30 días, las cinco compuertas no van a habilitar una operación todos los días. La restricción real no es el almanaque, son los setups válidos. Tus primeras 30 operaciones registradas los van a reemplazar por datos tuyos, y con esos números hay que rehacer la tabla del camino.</p>",
    "  <p>Este documento describe un procedimiento de gestión de riesgo y ejecución. No es asesoramiento financiero ni una promesa de resultados: el mercado no está obligado a producir setups válidos ni a respetar la tasa de aciertos supuesta. La decisión de operar y el capital comprometido son tuyos.</p>",
    "</footer>"
  ].join('\n');

  window.Sistema4K = { css: CSS, html: HTML };
})();
